import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, ArrowUpRight, BarChart3, Building2, Clock3, Eye, FileCheck2, Flag, HandCoins, Heart, MessageSquareText, ShieldAlert, UserRound, Users } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';

export function AdminDashboard(){const q=useQuery({queryKey:['admin-dashboard'],queryFn:()=>api<any>('/api/v2/admin/dashboard?period=30')});const d=q.data||{};return <AdminShell title="Operativni pregled" description="Najvažniji signali platforme u posljednjih 30 dana."><div className="kpi-grid"><Kpi icon={<Users/>} label="Aktivni korisnici" value={d.aktivniKorisnici||0} delta={d.deltaKorisnici}/><Kpi icon={<FileCheck2/>} label="Objavljeni oglasi" value={d.objavljeniOglasi||0}/><Kpi icon={<MessageSquareText/>} label="Novi razgovori" value={d.razgovori||0}/><Kpi icon={<Clock3/>} label="Čeka provjeru" value={d.cekaModeraciju||0} warn/></div><div className="admin-grid"><section className="panel wide"><div className="panel-heading"><div><span className="kicker">Konverzija</span><h2>Put korisnika do dogovora</h2></div><Link to="/admin/analitika">Detaljna analitika <ArrowUpRight/></Link></div><Funnel data={d.funnel}/></section><section className="panel"><span className="kicker">Pažnja</span><h2>Operativni red</h2><Queue label="Oglasi na provjeri" value={d.cekaModeraciju||0}/><Queue label="Agencije na provjeri" value={d.agencijeNaCekanju||0}/><Queue label="Prijave sadržaja" value={d.otvorenePrijave||0}/></section></div></AdminShell>}
export function AnalyticsPage(){const q=useQuery({queryKey:['admin-analytics'],queryFn:()=>api<any>('/api/v2/admin/analitika?period=30')});const d=q.data||{};return <AdminShell title="Analitika" description="Aktivnosti i konverzije bez uvida u privatni sadržaj."><div className="period-tabs"><button className="active">30 dana</button><button>7 dana</button><button>90 dana</button><button>Prilagođeno</button></div><div className="kpi-grid"><Kpi icon={<Eye/>} label="Pregledi" value={d.pregledi||0}/><Kpi icon={<Heart/>} label="Favoriti" value={d.favoriti||0}/><Kpi icon={<MessageSquareText/>} label="Razgovori" value={d.razgovori||0}/><Kpi icon={<HandCoins/>} label="Ponude" value={d.ponude||0}/></div><section className="panel"><h2>Konverzijski funnel</h2><Funnel data={d.funnel}/></section></AdminShell>}
export function UsersPage(){const q=useQuery({queryKey:['admin-users'],queryFn:()=>api<any[]>('/api/v2/admin/korisnici')});return <AdminShell title="Korisnici" description="Status naloga, uloge i posljednja aktivnost."><div className="table-wrap"><table><thead><tr><th>Korisnik</th><th>Uloga</th><th>Status</th><th>Aktivnost</th><th/></tr></thead><tbody>{q.data?.map(u=><tr key={u.id}><td><strong>{u.ime} {u.prezime}</strong><small>@{u.username}</small></td><td>{u.systemRole}</td><td><span className={`status ${u.suspendedAt?'declined':'confirmed'}`}>{u.suspendedAt?'Suspendovan':'Aktivan'}</span></td><td>{u.lastActivityAt?new Date(u.lastActivityAt).toLocaleString('bs-BA'):'—'}</td><td><Link to={`/admin/korisnici/${u.id}`}>Detalji</Link></td></tr>)}</tbody></table></div></AdminShell>}
export function UserDetailPage(){const {id}=useParams();const client=useQueryClient();const q=useQuery({queryKey:['admin-user',id],queryFn:()=>api<any>(`/api/v2/admin/korisnici/${id}`)});const action=useMutation({mutationFn:(akcija:string)=>api(`/api/v2/admin/korisnici/${id}`,{method:'PATCH',body:JSON.stringify({akcija,razlog:akcija==='SUSPEND'?'Ručna administratorska suspenzija':'Ponovna aktivacija naloga'})}),onSuccess:()=>client.invalidateQueries({queryKey:['admin-user',id]})});return <AdminShell title={q.data?`${q.data.ime} ${q.data.prezime}`:'Korisnik'} description="Metapodaci aktivnosti iz posljednjih 12 mjeseci."><div className="admin-grid"><section className="panel"><h2>Status naloga</h2><p>@{q.data?.username}</p><p>{q.data?.email||'Email nije dodat'}</p>{q.data?.suspendedAt?<button className="button" onClick={()=>action.mutate('REACTIVATE')}>Ponovo aktiviraj</button>:<button className="button danger" onClick={()=>action.mutate('SUSPEND')}>Suspenduj nalog</button>}</section><section className="panel wide"><h2>Timeline aktivnosti</h2><div className="timeline">{q.data?.aktivnosti?.map((a:any)=><div key={a.id}><Activity/><span><strong>{a.tip}</strong><small>{new Date(a.createdAt).toLocaleString('bs-BA')}</small></span></div>)}</div></section></div></AdminShell>}
export function ModerationPage({kind='moderation'}:{kind?:string}){const client=useQueryClient();const q=useQuery({queryKey:['admin-queue',kind],queryFn:()=>api<any[]>(`/api/v2/admin/${kind}`)});const act=useMutation({mutationFn:({id,akcija}:{id:number;akcija:string})=>api(`/api/v2/admin/${kind}/${id}`,{method:'PATCH',body:JSON.stringify({akcija,razlog:'Administratorska provjera'})}),onSuccess:()=>client.invalidateQueries({queryKey:['admin-queue',kind]})});return <AdminShell title={kind==='organizacije'?'Agencije':kind==='nekretnine'?'Oglasi':'Moderacija'} description="Pregledajte prijave i zahtjeve koji čekaju odluku."><div className="data-grid">{q.data?.map(x=><article className="data-card" key={x.id}><span className="status pending">{x.status||x.tip}</span><h3>{x.naziv||x.naslov||`Predmet #${x.id}`}</h3><p>{x.opis||x.razlog||'Potrebna je administratorska provjera.'}</p><div className="card-actions"><button className="button small" onClick={()=>act.mutate({id:x.id,akcija:'APPROVE'})}>Odobri</button><button className="button ghost small" onClick={()=>act.mutate({id:x.id,akcija:'REJECT'})}>Odbij</button></div></article>)}</div></AdminShell>}
export function ActivityPage(){const q=useQuery({queryKey:['admin-activity'],queryFn:()=>api<any[]>('/api/v2/admin/aktivnosti')});return <AdminShell title="Aktivnosti" description="Audit administratorskih odluka i sanitizirani događaji korisnika."><div className="timeline panel">{q.data?.map(a=><div key={a.id}><Activity/><span><strong>{a.tip}</strong><small>{a.actor?.username||'Sistem'} · {new Date(a.createdAt).toLocaleString('bs-BA')}</small></span></div>)}</div></AdminShell>}

function AdminShell({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="container page admin-page"><div className="admin-header"><div><span className="kicker">Admin centar</span><h1>{title}</h1><p>{description}</p></div><nav><Link to="/admin"><BarChart3/> Pregled</Link><Link to="/admin/analitika"><Activity/> Analitika</Link><Link to="/admin/korisnici"><UserRound/> Korisnici</Link><Link to="/admin/oglasi"><FileCheck2/> Oglasi</Link><Link to="/admin/agencije"><Building2/> Agencije</Link><Link to="/admin/moderacija"><Flag/> Moderacija</Link></nav></div>{children}</div>}
function Kpi({icon,label,value,delta,warn}:{icon:React.ReactNode;label:string;value:number;delta?:number;warn?:boolean}){return <div className={warn?'kpi warn':'kpi'}><span>{icon}</span><div><small>{label}</small><strong>{value.toLocaleString('bs-BA')}</strong>{delta!=null&&<em>{delta>=0?'+':''}{delta}%</em>}</div></div>}
function Funnel({data}:{data?:Record<string,number>}){const rows=[['Pregledi',data?.pregledi||0],['Favoriti',data?.favoriti||0],['Razgovori',data?.razgovori||0],['Termini',data?.termini||0],['Ponude',data?.ponude||0],['Zaključeno',data?.zakljuceno||0]];const max=Math.max(...rows.map(x=>Number(x[1])),1);return <div className="funnel">{rows.map(([label,val])=><div key={String(label)}><span>{label}</span><div><i style={{width:`${Math.max(4,Number(val)/max*100)}%`}}/></div><strong>{val}</strong></div>)}</div>}
function Queue({label,value}:{label:string;value:number}){return <Link className="queue-row" to="/admin/moderacija"><ShieldAlert/><span>{label}</span><strong>{value}</strong></Link>}
