import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Filter, Map, Search, SlidersHorizontal, X } from 'lucide-react';
import { MapContainer, Marker, Popup, TileLayer, useMapEvents } from 'react-leaflet';
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { api, apiEnvelope, money } from '../lib/api';
import type { Nekretnina, SearchCriteria } from '../types';
import { PropertyCard } from '../components/PropertyCard';
import { useAuth } from '../auth/AuthContext';

type Meta={page:number;pageSize:number;total:number;totalPages:number};
type MarkerItem=Pick<Nekretnina,'id'|'slug'|'naziv'|'cijena'|'latPriblizno'|'lngPriblizno'>&{thumbnail?:string};
const filterKeys=['lokacija','tip','namjena','cijenaMin','cijenaMax','kvadraturaMin','kvadraturaMax','sobeMin','kupatilaMin','parking','balkon','lift','namjestenost','stanje','energetskaKlasa','dostupnoOd','sort'];

export function ListingsPage(){
 const [params,setParams]=useSearchParams();const {user}=useAuth();const navigate=useNavigate();const location=useLocation();const [mapOpen,setMapOpen]=useState(false);const [moreOpen,setMoreOpen]=useState(false);const [saveOpen,setSaveOpen]=useState(false);const [locationInput,setLocationInput]=useState(params.get('lokacija')||'');
 useEffect(()=>setLocationInput(params.get('lokacija')||''),[params]);
 useEffect(()=>{const timer=setTimeout(()=>{const current=params.get('lokacija')||'';if(current===locationInput)return;const next=new URLSearchParams(params);locationInput?next.set('lokacija',locationInput):next.delete('lokacija');next.delete('page');setParams(next,{replace:true})},350);return()=>clearTimeout(timer)},[locationInput,params,setParams]);
 const apiParams=useMemo(()=>{const next=new URLSearchParams();for(const key of filterKeys)params.get(key)&&next.set(key,params.get(key)!);if(params.get('bbox'))next.set('bbox',params.get('bbox')!);next.set('page',params.get('page')||'1');next.set('pageSize','24');return next},[params]);
 const query=useQuery({queryKey:['properties',apiParams.toString()],queryFn:()=>apiEnvelope<Nekretnina[],Meta>(`/api/v2/nekretnine?${apiParams}`),placeholderData:p=>p});
 const update=(key:string,value:string)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key!=='page')next.delete('page');setParams(next)};
 const active=filterKeys.filter(key=>key!=='sort'&&params.has(key));const criteria=Object.fromEntries(filterKeys.filter(k=>params.has(k)).map(k=>{const raw=params.get(k)!;return[k,['cijenaMin','cijenaMax','kvadraturaMin','kvadraturaMax','sobeMin','kupatilaMin'].includes(k)?Number(raw):['parking','balkon','lift'].includes(k)?raw==='true':raw]})) as SearchCriteria;
 const page=query.data?.meta.page||1,totalPages=query.data?.meta.totalPages||1;
 const changePage=(next:number)=>{update('page',String(next));requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}))};
 return <div className="page container listings-page">
  <div className="page-heading"><div><span className="kicker">Istražite ponudu</span><h1>Nekretnine</h1><p>{query.data?.meta.total??'—'} oglasa odgovara vašoj pretrazi</p></div><div className="heading-actions"><button className="button secondary" onClick={()=>user?setSaveOpen(true):navigate(`/prijava?next=${encodeURIComponent(location.pathname+location.search)}`)}><SlidersHorizontal/> Sačuvaj pretragu</button><button className="button ghost" onClick={()=>setMapOpen(true)}><Map/> Prikaži mapu</button></div></div>
  <div className="listing-toolbar">
   <label className="search-field"><Search/><input value={locationInput} onChange={e=>setLocationInput(e.target.value)} placeholder="Grad, naselje ili lokacija"/></label>
   <Select label="Tip nekretnine" value={params.get('tip')||''} onChange={v=>update('tip',v)} options={[['','Svi tipovi'],['Stan','Stan'],['Kuća','Kuća'],['Poslovni prostor','Poslovni prostor']]}/>
   <Select label="Namjena" value={params.get('namjena')||''} onChange={v=>update('namjena',v)} options={[['','Prodaja i najam'],['PRODAJA','Prodaja'],['NAJAM','Najam']]}/>
   <Select label="Sortiranje" value={params.get('sort')||'najnovije'} onChange={v=>update('sort',v)} options={[['najnovije','Najnovije'],['cijena-asc','Cijena: niža prvo'],['cijena-desc','Cijena: viša prvo'],['kvadratura-desc','Najveća kvadratura']]}/>
   <button className="button ghost" aria-expanded={moreOpen} onClick={()=>setMoreOpen(v=>!v)}><Filter/> Više filtera</button>
  </div>
  {moreOpen&&<MoreFilters params={params} update={update}/>}
  {!!active.length&&<div className="active-filters">{active.map(key=><button key={key} onClick={()=>update(key,'')}>{filterLabel(key,params.get(key)!)} <X/></button>)}<button className="clear-filters" onClick={()=>setParams(new URLSearchParams())}>Očisti sve</button></div>}
  {query.isLoading?<div className="card-grid">{Array.from({length:6},(_,i)=><div className="skeleton card-skeleton" key={i}/>)}</div>:query.isError?<div className="empty-state"><h2>Rezultate trenutno nije moguće učitati</h2><p>{query.error.message}</p><button className="button" onClick={()=>query.refetch()}>Pokušaj ponovo</button></div>:query.data?.data.length?<><div className="card-grid">{query.data.data.map(item=><PropertyCard key={item.id} item={item}/>)}</div><nav className="pagination" aria-label="Stranice rezultata"><button disabled={page<=1} onClick={()=>changePage(page-1)}>Prethodna</button><span>Stranica {page} od {totalPages}</span><button disabled={page>=totalPages} onClick={()=>changePage(page+1)}>Sljedeća</button></nav></>:<div className="empty-state"><h2>Nema rezultata</h2><p>Pokušajte proširiti lokaciju ili ukloniti neki filter.</p><button className="button secondary" onClick={()=>setParams(new URLSearchParams())}>Prikaži sve oglase</button></div>}
  {mapOpen&&<MapPanel apiParams={apiParams} onClose={()=>setMapOpen(false)} onBounds={bbox=>update('bbox',bbox)}/>} {saveOpen&&<SaveSearchDialog criteria={criteria} onClose={()=>setSaveOpen(false)}/>}
 </div>
}

function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>}
function MoreFilters({params,update}:{params:URLSearchParams;update:(k:string,v:string)=>void}){return <section className="more-filters" aria-label="Dodatni filteri"><label>Cijena od<input type="number" min="0" value={params.get('cijenaMin')||''} onChange={e=>update('cijenaMin',e.target.value)}/></label><label>Cijena do<input type="number" min="0" value={params.get('cijenaMax')||''} onChange={e=>update('cijenaMax',e.target.value)}/></label><label>Kvadratura od<input type="number" min="0" value={params.get('kvadraturaMin')||''} onChange={e=>update('kvadraturaMin',e.target.value)}/></label><label>Kvadratura do<input type="number" min="0" value={params.get('kvadraturaMax')||''} onChange={e=>update('kvadraturaMax',e.target.value)}/></label><label>Minimalno soba<input type="number" min="0" value={params.get('sobeMin')||''} onChange={e=>update('sobeMin',e.target.value)}/></label><label>Minimalno kupatila<input type="number" min="0" value={params.get('kupatilaMin')||''} onChange={e=>update('kupatilaMin',e.target.value)}/></label><label>Namještenost<input value={params.get('namjestenost')||''} onChange={e=>update('namjestenost',e.target.value)} placeholder="Namješteno"/></label><label>Stanje<input value={params.get('stanje')||''} onChange={e=>update('stanje',e.target.value)} placeholder="npr. Novogradnja"/></label><label>Energetska klasa<input value={params.get('energetskaKlasa')||''} onChange={e=>update('energetskaKlasa',e.target.value)} placeholder="A–G"/></label><label>Dostupno do<input type="date" value={params.get('dostupnoOd')||''} onChange={e=>update('dostupnoOd',e.target.value)}/></label>{[['parking','Parking'],['balkon','Balkon'],['lift','Lift']].map(([key,label])=><label className="check-filter" key={key}><input type="checkbox" checked={params.get(key)==='true'} onChange={e=>update(key,e.target.checked?'true':'')}/>{label}</label>)}</section>}
function MapPanel({apiParams,onClose,onBounds}:{apiParams:URLSearchParams;onClose:()=>void;onBounds:(bbox:string)=>void}){const mapParams=new URLSearchParams(apiParams);mapParams.delete('page');mapParams.delete('pageSize');const q=useQuery({queryKey:['property-map',mapParams.toString()],queryFn:()=>api<MarkerItem[]>(`/api/v2/nekretnine/mapa?${mapParams}`)});const [bounds,setBounds]=useState('');return <div className="map-panel" role="dialog" aria-modal="true" aria-label="Mapa nekretnina"><div className="map-panel-head"><div><strong>Približne lokacije</strong><span>{q.data?.length||0} oglasa na mapi</span></div><button onClick={onClose} aria-label="Zatvori mapu"><X/></button></div><MapContainer className="search-map" center={[44.1,17.8]} zoom={7} scrollWheelZoom><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><BoundsWatcher onChange={setBounds}/>{q.data?.filter(x=>x.latPriblizno&&x.lngPriblizno).map(x=><Marker key={x.id} position={[Number(x.latPriblizno),Number(x.lngPriblizno)]}><Popup><div className="map-popup">{x.thumbnail&&<img src={x.thumbnail} alt=""/>}<strong>{x.naziv}</strong><span>{money(x.cijena)}</span><Link to={`/nekretnine/${x.slug||x.id}`}>Otvori oglas</Link></div></Popup></Marker>)}</MapContainer>{bounds&&<button className="button map-search-area" onClick={()=>{onBounds(bounds);onClose()}}>Pretraži ovo područje</button>}</div>}
function BoundsWatcher({onChange}:{onChange:(v:string)=>void}){useMapEvents({moveend:e=>{const b=e.target.getBounds();onChange([b.getWest(),b.getSouth(),b.getEast(),b.getNorth()].map((x:number)=>x.toFixed(5)).join(','))}});return null}
function SaveSearchDialog({criteria,onClose}:{criteria:SearchCriteria;onClose:()=>void}){const mutation=useMutation({mutationFn:(name:string)=>api('/api/v2/sacuvane-pretrage',{method:'POST',body:JSON.stringify({naziv:name,kriteriji:criteria,alertsEnabled:true})}),onSuccess:onClose});const suggested=criteria.lokacija?`Nekretnine — ${criteria.lokacija}`:'Moja pretraga';return <div className="dialog-backdrop"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="save-search-title"><button className="dialog-close" onClick={onClose} aria-label="Zatvori"><X/></button><span className="kicker">Obavijesti o novim oglasima</span><h2 id="save-search-title">Sačuvajte ovu pretragu</h2><p>Obavijestit ćemo vas u aplikaciji čim se objavi odgovarajući oglas.</p><form onSubmit={e=>{e.preventDefault();mutation.mutate(String(new FormData(e.currentTarget).get('naziv')))}}><label>Naziv pretrage<input name="naziv" defaultValue={suggested} minLength={2} maxLength={100} required/></label><div className="criteria-summary">{Object.entries(criteria).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=><span key={k}>{filterLabel(k,String(v))}</span>)}</div>{mutation.error&&<p className="form-error">{mutation.error.message}</p>}<button className="button full" disabled={mutation.isPending}>{mutation.isPending?'Čuvam…':'Sačuvaj i uključi alerte'}</button></form></div></div>}
function filterLabel(key:string,value:string){const labels:Record<string,string>={lokacija:'Lokacija',tip:'Tip',namjena:'Namjena',cijenaMin:'Cijena od',cijenaMax:'Cijena do',kvadraturaMin:'Kvadratura od',kvadraturaMax:'Kvadratura do',sobeMin:'Sobe',kupatilaMin:'Kupatila',parking:'Parking',balkon:'Balkon',lift:'Lift',namjestenost:'Namještenost',stanje:'Stanje',energetskaKlasa:'Energetska klasa',dostupnoOd:'Dostupno'};return `${labels[key]||key}: ${value==='true'?'Da':value}`}
