import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, ChevronLeft, ChevronRight, GripVertical, ImagePlus, MapPin, Save, Send, Star, Trash2, UploadCloud } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { useForm } from 'react-hook-form';
import { CircleMarker, MapContainer, TileLayer, useMapEvents } from 'react-leaflet';
import { useNavigate, useParams } from 'react-router-dom';
import { z } from 'zod';
import { api, ApiError, imageUrl, money } from '../lib/api';
import type { ListingEditorPayload } from '../types';

const schema=z.object({
 naziv:z.string().min(8,'Najmanje 8 znakova'),tip_nekretnine:z.string().min(1),namjena:z.enum(['PRODAJA','NAJAM']),
 kvadratura:z.coerce.number().positive(),cijena:z.coerce.number().positive(),lokacija:z.string().min(2),grad:z.string().optional(),naselje:z.string().optional(),punaAdresa:z.string().optional(),
 opis:z.string().min(40,'Najmanje 40 znakova'),tip_grijanja:z.string().optional(),godina_izgradnje:z.coerce.number().optional().nullable(),brojSoba:z.coerce.number().optional().nullable(),brojKupatila:z.coerce.number().optional().nullable(),sprat:z.coerce.number().optional().nullable(),brojSpratova:z.coerce.number().optional().nullable(),
 parking:z.boolean().optional(),balkon:z.boolean().optional(),lift:z.boolean().optional(),namjestenost:z.string().optional(),stanje:z.string().optional(),energetskaKlasa:z.string().optional(),dostupnoOd:z.string().optional(),latTacno:z.number().optional(),lngTacno:z.number().optional(),
});
type DraftForm=z.infer<typeof schema>;
const steps=['Osnovno','Karakteristike','Lokacija','Fotografije','Kontakt','Preview'];

function LocationPicker({lat,lng,onPick}:{lat?:number;lng?:number;onPick:(lat:number,lng:number)=>void}){useMapEvents({click:e=>onPick(e.latlng.lat,e.latlng.lng)});return lat&&lng?<CircleMarker center={[lat,lng]} radius={10} pathOptions={{color:'#26734d',fillOpacity:.9}}/>:null}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label>{label}{children}{error&&<span className="field-error">{error}</span>}</label>}
function Progress({label,done}:{label:string;done:boolean}){return <div className={done?'progress-item done':'progress-item'}>{done?<Check/>:<span/>}<b>{label}</b></div>}

export function ListingEditorPage(){
 const params=useParams(),id=params.id;const navigate=useNavigate(),client=useQueryClient();const creating=useRef(false),hydrated=useRef(false),version=useRef(1);const [step,setStep]=useState(0),[saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle'),[dragId,setDragId]=useState<number>(),[serverErrors,setServerErrors]=useState<Record<string,string>>({});
 const create=useMutation({mutationFn:()=>api<{id:number}>('/api/v2/moji-oglasi',{method:'POST',body:'{}'}),onSuccess:x=>navigate(`/moji-oglasi/${x.id}/uredi`,{replace:true})});
 useEffect(()=>{if(!id&&!creating.current){creating.current=true;create.mutate()}},[id]);
 const query=useQuery({queryKey:['listing-editor',id],queryFn:()=>api<ListingEditorPayload>(`/api/v2/moji-oglasi/${id}/editor`),enabled:!!id});
 const form=useForm<DraftForm>({resolver:zodResolver(schema),defaultValues:{tip_nekretnine:'Stan',namjena:'PRODAJA',parking:false,balkon:false,lift:false,opis:'',naziv:'',lokacija:'',kvadratura:0,cijena:0}}),{register,reset,watch,setValue,getValues,formState:{errors}}=form;
 useEffect(()=>{if(query.data&&!hydrated.current){reset(query.data.draft.podaci as DraftForm);version.current=query.data.draft.verzija;setStep(Math.min(5,query.data.draft.dovrseniKorak||0));hydrated.current=true}},[query.data,reset]);
 const save=useMutation({mutationFn:({values,completed}:{values:DraftForm;completed:number})=>api<{verzija:number}>(`/api/v2/moji-oglasi/${id}/draft`,{method:'PATCH',headers:{'If-Match':String(version.current)},body:JSON.stringify({podaci:values,dovrseniKorak:completed})}),onMutate:()=>setSaveState('saving'),onSuccess:r=>{version.current=r.verzija;setSaveState('saved')},onError:()=>setSaveState('error')});
 useEffect(()=>{if(!id||!hydrated.current)return;let timer:number;const sub=watch(()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>save.mutate({values:getValues(),completed:step}),800)});return()=>{window.clearTimeout(timer);sub.unsubscribe()}},[id,watch,getValues,step]);
 const submit=useMutation({mutationFn:()=>api(`/api/v2/moji-oglasi/${id}/submit`,{method:'POST',body:'{}'}),onSuccess:()=>navigate('/moji-oglasi'),onError:(e:ApiError)=>setServerErrors(e.fieldErrors||{})});
 const upload=useMutation({mutationFn:async(files:File[])=>{for(const file of files){const data=new globalThis.FormData();data.append('slika',file);await api(`/api/v2/moji-oglasi/${id}/fotografije`,{method:'POST',body:data})}},onSuccess:()=>client.invalidateQueries({queryKey:['listing-editor',id]})});
 const arrange=useMutation({mutationFn:({ids,coverId}:{ids:number[];coverId:number})=>api(`/api/v2/moji-oglasi/${id}/fotografije`,{method:'PATCH',body:JSON.stringify({ids,coverId})}),onSuccess:()=>client.invalidateQueries({queryKey:['listing-editor',id]})});
 const remove=useMutation({mutationFn:(imageId:number)=>api(`/api/v2/moji-oglasi/${id}/fotografije/${imageId}`,{method:'DELETE'}),onSuccess:()=>client.invalidateQueries({queryKey:['listing-editor',id]})});
 if(!id||query.isLoading)return <div className="container page"><div className="skeleton detail-skeleton"/><p>{create.isPending?'Kreiram siguran draft…':'Učitavam editor…'}</p></div>;
 if(!query.data)return <div className="container page empty-state"><h1>Editor nije dostupan</h1><p>{String(query.error||create.error||'Pokušajte ponovo.')}</p></div>;
 const images=query.data.images||[],values=watch(),lat=Number(values.latTacno)||undefined,lng=Number(values.lngTacno)||undefined;
 const go=async(next:number)=>{if(next>step&&step===0&&!await form.trigger(['naziv','tip_nekretnine','namjena','kvadratura','cijena','opis']))return;setStep(Math.max(0,Math.min(5,next)))};
 const reorder=(target:number)=>{if(!dragId||dragId===target)return;const ids=images.map(x=>x.id),from=ids.indexOf(dragId),to=ids.indexOf(target);ids.splice(to,0,ids.splice(from,1)[0]);arrange.mutate({ids,coverId:images.find(x=>x.glavna)?.id||ids[0]});setDragId(undefined)};
 return <div className="container page listing-wizard">
  <div className="wizard-heading"><div><span className="kicker">Profesionalni editor</span><h1>{values.naziv||'Novi oglas'}</h1><p>Izmjene ostaju privatni draft dok ih moderator ne odobri.</p></div><span className={`autosave ${saveState}`}><Save/>{saveState==='saving'?'Čuvanje…':saveState==='saved'?'Sačuvano':saveState==='error'?'Greška čuvanja':'Draft'}</span></div>
  <nav className="wizard-steps" aria-label="Koraci oglasa">{steps.map((s,i)=><button type="button" key={s} className={step===i?'active':i<step?'done':''} onClick={()=>go(i)}><span>{i<step?<Check/>:i+1}</span>{s}</button>)}</nav>
  <div className="wizard-layout"><main className="wizard-main">
   {step===0&&<section className="panel wizard-panel"><h2>Osnovni podaci</h2><div className="form-grid"><Field label="Naziv oglasa" error={errors.naziv?.message||serverErrors.naziv}><input {...register('naziv')} placeholder="Svijetao trosoban stan u Centru"/></Field><Field label="Tip"><select {...register('tip_nekretnine')}><option>Stan</option><option>Kuća</option><option>Poslovni prostor</option><option>Zemljište</option></select></Field><Field label="Namjena"><select {...register('namjena')}><option value="PRODAJA">Prodaja</option><option value="NAJAM">Najam</option></select></Field><Field label="Površina (m²)" error={errors.kvadratura?.message}><input type="number" min="1" {...register('kvadratura')}/></Field><Field label="Cijena (KM)" error={errors.cijena?.message}><input type="number" min="1" {...register('cijena')}/></Field><Field label="Dostupno od"><input type="date" {...register('dostupnoOd')}/></Field></div><Field label="Opis" error={errors.opis?.message||serverErrors.opis}><textarea rows={9} {...register('opis')} placeholder="Opišite raspored, stanje, lokaciju i posebne prednosti…"/></Field></section>}
   {step===1&&<section className="panel wizard-panel"><h2>Karakteristike</h2><div className="form-grid"><Field label="Broj soba"><input type="number" min="0" {...register('brojSoba')}/></Field><Field label="Kupatila"><input type="number" min="0" {...register('brojKupatila')}/></Field><Field label="Sprat"><input type="number" {...register('sprat')}/></Field><Field label="Ukupno spratova"><input type="number" min="0" {...register('brojSpratova')}/></Field><Field label="Godina izgradnje"><input type="number" min="1800" {...register('godina_izgradnje')}/></Field><Field label="Grijanje"><input {...register('tip_grijanja')}/></Field><Field label="Stanje"><select {...register('stanje')}><option value="">Odaberite</option><option>Novo</option><option>Renovirano</option><option>Useljivo</option><option>Potrebno renoviranje</option></select></Field><Field label="Namještenost"><select {...register('namjestenost')}><option value="">Odaberite</option><option>Namješteno</option><option>Polunamješteno</option><option>Nenamješteno</option></select></Field><Field label="Energetska klasa"><select {...register('energetskaKlasa')}><option value="">Nije navedeno</option>{['A+','A','B','C','D','E','F','G'].map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="check-grid"><label><input type="checkbox" {...register('parking')}/> Parking</label><label><input type="checkbox" {...register('balkon')}/> Balkon</label><label><input type="checkbox" {...register('lift')}/> Lift</label></div></section>}
   {step===2&&<section className="panel wizard-panel"><h2>Lokacija i privatnost</h2><div className="form-grid"><Field label="Javna lokacija" error={errors.lokacija?.message||serverErrors.lokacija}><input {...register('lokacija')} placeholder="Sarajevo, Centar"/></Field><Field label="Grad"><input {...register('grad')}/></Field><Field label="Naselje"><input {...register('naselje')}/></Field><Field label="Tačna adresa — privatna"><input {...register('punaAdresa')}/></Field></div><div className="location-note"><MapPin/><p>Kliknite mjesto nekretnine. Tačna koordinata ostaje privatna; javna mapa dobija zaštićenu približnu tačku.</p></div><MapContainer center={[lat||43.8563,lng||18.4131]} zoom={lat?15:12} className="editor-map"><TileLayer attribution="&copy; OpenStreetMap" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><LocationPicker lat={lat} lng={lng} onPick={(a,b)=>{setValue('latTacno',a,{shouldDirty:true});setValue('lngTacno',b,{shouldDirty:true})}}/></MapContainer></section>}
   {step===3&&<section className="panel wizard-panel"><h2>Fotografije</h2><label className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload.mutate([...e.dataTransfer.files].slice(0,12-images.length))}}><UploadCloud/><strong>Povucite fotografije ili odaberite datoteke</strong><span>JPG, PNG ili WebP · do 12 fotografija</span><input hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>upload.mutate([...e.target.files||[]].slice(0,12-images.length))}/></label>{upload.error&&<p className="form-error">{upload.error.message}</p>}<div className="photo-sort">{images.map(image=><article key={image.id} draggable onDragStart={()=>setDragId(image.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>reorder(image.id)}><img src={imageUrl(image,'thumbnail')} alt="Fotografija oglasa"/><GripVertical className="grip"/><button type="button" className={image.glavna?'cover active':'cover'} onClick={()=>arrange.mutate({ids:images.map(x=>x.id),coverId:image.id})}><Star/> {image.glavna?'Naslovna':'Postavi naslovnu'}</button><button type="button" className="photo-delete" onClick={()=>remove.mutate(image.id)} aria-label="Obriši fotografiju"><Trash2/></button></article>)}</div>{!images.length&&<p className="field-error">{serverErrors.fotografije}</p>}</section>}
   {step===4&&<section className="panel wizard-panel"><h2>Vlasništvo i kontakt</h2><div className="review-list"><div><Check/><span><strong>Kontakt kroz Domus inbox</strong><small>Privatni podaci se ne objavljuju automatski.</small></span></div><div><Check/><span><strong>Odvojeni termini i ponude</strong><small>Zainteresovani korisnici biraju tačno željenu akciju.</small></span></div><div><Check/><span><strong>Moderirana objava</strong><small>Javna verzija se mijenja tek nakon odobrenja.</small></span></div></div>{!query.data.publishingAllowed&&<div className="notice">Nalog još nema beta dozvolu za objavljivanje. Draft možete dovršiti dok administrator odobrava pristup.</div>}</section>}
   {step===5&&<section className="panel wizard-panel preview-panel"><span className="status">Preview</span>{images[0]?<img className="preview-cover" src={imageUrl(images.find(x=>x.glavna)||images[0],'large')} alt="Naslovna fotografija"/>:<div className="preview-empty"><ImagePlus/> Dodajte naslovnu fotografiju</div>}<div className="preview-copy"><p>{values.tip_nekretnine} · {values.namjena==='NAJAM'?'Najam':'Prodaja'}</p><h2>{values.naziv||'Naziv oglasa'}</h2><strong>{money(values.cijena||0)}</strong><span><MapPin/> {values.lokacija||'Lokacija'}</span><div className="preview-facts"><b>{values.kvadratura||0} m²</b><b>{values.brojSoba||0} sobe</b><b>{values.brojKupatila||0} kupatila</b></div><p className="lead-copy">{values.opis}</p></div></section>}
   <div className="wizard-actions"><button type="button" className="button ghost" disabled={step===0} onClick={()=>go(step-1)}><ChevronLeft/> Nazad</button>{step<5?<button type="button" className="button" onClick={()=>go(step+1)}>Nastavi <ChevronRight/></button>:<button type="button" className="button" disabled={submit.isPending||!query.data.publishingAllowed} onClick={()=>submit.mutate()}><Send/> {submit.isPending?'Šaljem…':'Pošalji na provjeru'}</button>}</div>{submit.error&&<p className="form-error">{submit.error.message}</p>}
  </main><aside className="wizard-aside"><strong>Spremnost oglasa</strong><Progress label="Osnovni podaci" done={!!values.naziv&&Number(values.cijena)>0}/><Progress label="Opis" done={(values.opis?.length||0)>=40}/><Progress label="Lokacija" done={!!values.lokacija}/><Progress label="Fotografije" done={images.length>0}/><Progress label="Beta dozvola" done={query.data.publishingAllowed}/><hr/><small>Status</small><span className="status">{query.data.listing.status}</span>{query.data.history[0]?.razlogOdluke&&<p className="notice">{query.data.history[0].razlogOdluke}</p>}</aside></div>
 </div>
}
