import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, Building2, CalendarDays, ChevronRight, HandCoins, Inbox, MessageSquareText, Plus, ShieldCheck } from 'lucide-react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { api, money } from '../lib/api';
import type { Conversation, FavoritesPayload, Nekretnina, Notification, SavedSearch } from '../types';
import { PropertyCard } from '../components/PropertyCard';

export function Protected({ children, admin=false }: { children: React.ReactNode; admin?: boolean }) { const {user,loading}=useAuth(); if(loading)return <div className="container page"><div className="skeleton detail-skeleton"/></div>; if(!user)return <Navigate to="/prijava" replace/>; if(admin&&user.systemRole==='USER')return <Navigate to="/" replace/>; return children; }

export function InboxPage() {
 const q=useQuery({queryKey:['conversations'],queryFn:()=>api<Conversation[]>('/api/v2/razgovori')});
 return <Workspace title="Inbox" description="Privatni razgovori vezani za konkretne oglase."><div className="conversation-list">{q.data?.map(c=><Link to={`/inbox/${c.id}`} className="conversation-row" key={c.id}><div className="avatar"><MessageSquareText/></div><div><strong>{c.Nekretnina.naziv}</strong><span>{c.drugaStrana?.naziv || c.Nekretnina.lokacija}</span><p>{c.zadnjaPoruka || 'Razgovor je otvoren.'}</p></div><div><small>{new Date(c.updatedAt).toLocaleDateString('bs-BA')}</small>{!!c.neprocitano&&<b>{c.neprocitano}</b>}<ChevronRight/></div></Link>) || <Empty icon={<Inbox/>} title="Inbox je prazan" text="Kada pošaljete poruku s oglasa, razgovor će se pojaviti ovdje."/>}</div></Workspace>;
}
export function ConversationPage(){const {id}=useParams();const client=useQueryClient();const q=useQuery({queryKey:['conversation',id],queryFn:()=>api<any>(`/api/v2/razgovori/${id}`)});const send=useMutation({mutationFn:(tekst:string)=>api(`/api/v2/razgovori/${id}/poruke`,{method:'POST',body:JSON.stringify({tekst})}),onSuccess:()=>client.invalidateQueries({queryKey:['conversation',id]})});const faq=useMutation({mutationFn:(v:{pitanje:string;odgovor:string})=>api(`/api/v2/razgovori/${id}/faq`,{method:'POST',body:JSON.stringify(v)})});const report=useMutation({mutationFn:(messageId:number)=>api('/api/v2/prijave',{method:'POST',body:JSON.stringify({tip:'PORUKA',entitetId:messageId,razlog:'Neprimjeren ili sumnjiv sadržaj poruke'})})});return <Workspace title={q.data?.Nekretnina?.naziv||'Razgovor'} description="Sadržaj ovog razgovora je privatan."><div className="chat"><div className="messages">{q.data?.Poruke?.map((m:any)=><div className={m.jeMoja?'message mine':'message'} key={m.id}><p>{m.tekst}</p><small>{new Date(m.createdAt).toLocaleString('bs-BA')}</small>{!m.jeMoja&&<button className="message-report" onClick={()=>report.mutate(m.id)}>Prijavi</button>}</div>)}</div><form className="composer" onSubmit={e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('tekst') as HTMLInputElement;if(input.value.trim()){send.mutate(input.value.trim());input.value='';}}}><input name="tekst" placeholder="Napišite poruku…"/><button className="button">Pošalji</button></form></div>{q.data?.jeVlasnik&&<form className="panel faq-publisher" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);faq.mutate({pitanje:String(f.get('pitanje')),odgovor:String(f.get('odgovor'))})}}><span className="kicker">Javni FAQ</span><h2>Objavite anonimizirani odgovor</h2><p>Preformulišite korisno pitanje. Identitet i privatni razgovor neće biti objavljeni.</p><input name="pitanje" placeholder="Javno pitanje" required/><textarea name="odgovor" placeholder="Javni odgovor" rows={4} required/><button className="button">Objavi FAQ</button>{faq.isSuccess&&<span className="verified">FAQ je objavljen.</span>}</form>}</Workspace>}

export function AppointmentsPage(){const q=useQuery({queryKey:['appointments'],queryFn:()=>api<any[]>('/api/v2/termini')});return <Workspace title="Termini pregleda" description="Svi prijedlozi i potvrđeni obilasci na jednom mjestu."><DataCards items={q.data||[]} empty="Još nemate zakazanih pregleda" render={(x:any)=><><span className={`status ${x.status?.toLowerCase()}`}>{x.status}</span><h3>{x.Nekretnina?.naziv}</h3><p><CalendarDays/> {new Date(x.predlozeniTermin).toLocaleString('bs-BA')}</p></>}/></Workspace>}
export function OffersPage(){const q=useQuery({queryKey:['offers'],queryFn:()=>api<any[]>('/api/v2/pregovaracke-ponude')});return <Workspace title="Ponude" description="Pregled neobavezujućih ponuda i kontra-ponuda."><div className="notice"><ShieldCheck/> Ponude na Domusu nisu ugovor niti rezervacija.</div><DataCards items={q.data||[]} empty="Još nemate poslanih ponuda" render={(x:any)=><><span className={`status ${x.status?.toLowerCase()}`}>{x.status}</span><h3>{x.Nekretnina?.naziv}</h3><strong className="large-number">{money(x.iznos)}</strong></>}/></Workspace>}
export function MyListingsPage(){const q=useQuery({queryKey:['my-listings'],queryFn:()=>api<Nekretnina[]>('/api/nekretnine/moje')});return <Workspace title="Moji oglasi" description="Upravljajte sadržajem, statusom provjere i rezultatima oglasa." action={<Link className="button" to="/moji-oglasi/novi"><Plus/> Novi oglas</Link>}><DataCards items={q.data||[]} empty="Još nemate oglasa" render={(x:Nekretnina)=><><span className="status">{x.status||'DRAFT'}</span><h3>{x.naziv}</h3><p>{x.lokacija} · {x.kvadratura} m²</p><Link className="text-link" to={`/nekretnine/${x.slug||x.id}`}>Otvori oglas <ChevronRight/></Link></>}/></Workspace>}
export function SavedPage(){const client=useQueryClient();const favorites=useQuery({queryKey:['favorites'],queryFn:()=>api<FavoritesPayload>('/api/v2/omiljene')});const searches=useQuery({queryKey:['saved-searches'],queryFn:()=>api<SavedSearch[]>('/api/v2/sacuvane-pretrage')});const update=useMutation({mutationFn:({id,body}:{id:number;body:Partial<SavedSearch>})=>api(`/api/v2/sacuvane-pretrage/${id}`,{method:'PATCH',body:JSON.stringify(body)}),onSuccess:()=>client.invalidateQueries({queryKey:['saved-searches']})});const remove=useMutation({mutationFn:(id:number)=>api(`/api/v2/sacuvane-pretrage/${id}`,{method:'DELETE'}),onSuccess:()=>client.invalidateQueries({queryKey:['saved-searches']})});return <Workspace title="Sačuvano" description="Omiljeni oglasi i pretrage koje želite pratiti.">{favorites.data?.items.length?<div className="card-grid">{favorites.data.items.map(x=><PropertyCard item={x} key={x.id}/>)}</div>:<Empty icon={<ShieldCheck/>} title="Vaša kolekcija je prazna" text="Sačuvajte nekretnine kako biste ih lakše uporedili."/>}<section className="saved-searches"><div className="section-heading compact"><div><span className="kicker">Automatsko praćenje</span><h2>Sačuvane pretrage</h2></div></div>{searches.data?.length?<div className="data-grid">{searches.data.map(x=>{const qs=new URLSearchParams(Object.entries(x.kriteriji||{}).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=>[k,String(v)]));return <article className="data-card saved-search-card" key={x.id}><div><span className={x.alertsEnabled?'verified':'status'}>{x.alertsEnabled?'Alerti uključeni':'Alerti isključeni'}</span><h3>{x.naziv}</h3><p>{x.kriteriji?.lokacija||'Sve lokacije'} · {x.kriteriji?.tip||'Svi tipovi'}</p></div><div className="saved-search-actions"><Link className="button secondary" to={`/nekretnine?${qs}`}>Otvori</Link><button className="button ghost" onClick={()=>{const name=window.prompt('Novi naziv pretrage',x.naziv)?.trim();if(name&&name!==x.naziv)update.mutate({id:x.id,body:{naziv:name}})}}>Preimenuj</button><button className="button ghost" onClick={()=>update.mutate({id:x.id,body:{alertsEnabled:!x.alertsEnabled}})}>{x.alertsEnabled?'Isključi alerte':'Uključi alerte'}</button><button className="text-danger" onClick={()=>remove.mutate(x.id)}>Obriši</button></div></article>})}</div>:<div className="empty-inline"><Bell/><div><strong>Još nemate sačuvanih pretraga</strong><p>Postavite filtere na stranici nekretnina i uključite automatske alerte.</p></div></div>}</section></Workspace>}
export function NotificationsPage(){const client=useQueryClient();const q=useQuery({queryKey:['notifications'],queryFn:()=>api<Notification[]>('/api/v2/obavijesti')});const read=useMutation({mutationFn:(id:number)=>api(`/api/v2/obavijesti/${id}/procitano`,{method:'PATCH'}),onSuccess:()=>client.invalidateQueries({queryKey:['notifications']})});return <Workspace title="Obavijesti" description="Promjene koje zahtijevaju vašu pažnju."><div className="notification-list">{q.data?.map(n=><button key={n.id} className={n.procitanoAt?'notification read':'notification'} onClick={()=>{read.mutate(n.id);if(n.link)location.assign(n.link)}}><Bell/><span><strong>{n.naslov}</strong><p>{n.poruka}</p><small>{new Date(n.createdAt).toLocaleString('bs-BA')}</small></span></button>)||<Empty icon={<Bell/>} title="Sve je mirno" text="Nema novih obavijesti."/>}</div></Workspace>}
export function ProfilePage(){const {user}=useAuth();const client=useQueryClient();const email=useMutation({mutationFn:(value:string)=>api('/api/v2/auth/email',{method:'POST',body:JSON.stringify({email:value})}),onSuccess:()=>client.invalidateQueries({queryKey:['session']})});return <Workspace title="Profil" description="Identitet i sigurnosne postavke naloga."><div className="profile-card"><div className="avatar large">{user?.ime[0]}{user?.prezime[0]}</div><div><h2>{user?.ime} {user?.prezime}</h2><p>@{user?.username}</p><span className={user?.emailVerified?'verified':'status pending'}>{user?.emailVerified?'Email potvrđen':'Potvrdite email prije objave i komunikacije'}</span></div></div>{!user?.emailVerified&&<form className="panel profile-email" onSubmit={e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('email') as HTMLInputElement;email.mutate(input.value)}}><h2>{user?.email?'Ponovo pošaljite potvrdu':'Dodajte email adresu'}</h2><p>Sigurnosni link je potreban prije objavljivanja oglasa, slanja poruka i ponuda.</p><div className="composer"><input name="email" type="email" defaultValue={user?.email||''} required placeholder="ime@primjer.ba"/><button className="button">Pošalji link</button></div>{email.isSuccess&&<span className="verified">Link je poslan.</span>}{email.error&&<p className="form-error">{email.error.message}</p>}</form>}</Workspace>}
export function OrganizationPage(){const mutation=useMutation({mutationFn:(v:any)=>api('/api/v2/organizacije',{method:'POST',body:JSON.stringify(v)})});return <Workspace title="Moja organizacija" description="Agencijski profil, članovi tima i provjera identiteta.">{mutation.isSuccess?<div className="empty-state"><ShieldCheck/><h2>Zahtjev je poslan</h2><p>Agencija je kreirana i čeka administratorsku provjeru.</p></div>:<form className="panel organization-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate(Object.fromEntries(f))}}><span className="kicker">Agencijski onboarding</span><h2>Predstavite svoju agenciju</h2><p>Kreirajte organizaciju i pošaljite osnovne poslovne podatke na provjeru.</p><label>Naziv agencije<input name="naziv" required/></label><label>Grad<input name="grad" required/></label><label>Registracijski broj<input name="registracijskiBroj" required/></label><label>Opis<textarea name="opis" rows={5}/></label>{mutation.error&&<p className="form-error">{mutation.error.message}</p>}<button className="button"><Building2/> Pošalji na provjeru</button></form>}</Workspace>}
export function AgenciesPage(){const q=useQuery({queryKey:['agencies'],queryFn:()=>api<any[]>('/api/v2/organizacije')});return <div className="container page"><div className="page-heading"><div><span className="kicker">Pouzdani partneri</span><h1>Agencije</h1><p>Upoznajte timove koji stoje iza oglasa.</p></div></div><div className="data-grid">{q.data?.map(o=><Link className="data-card" to={`/agencije/${o.slug}`} key={o.id}><div className="avatar large">{o.naziv[0]}</div><span className="verified"><ShieldCheck/> Verificirana</span><h2>{o.naziv}</h2><p>{o.grad||'Bosna i Hercegovina'} · {o.brojOglasa||0} oglasa</p></Link>)}</div></div>}
export function AgencyPage(){const {slug}=useParams();const q=useQuery({queryKey:['agency',slug],queryFn:()=>api<any>(`/api/v2/organizacije/${slug}`)});return <div className="container page"><div className="agency-hero"><div className="avatar agency">{q.data?.naziv?.[0]||'A'}</div><div><span className="verified"><ShieldCheck/> Verificirana agencija</span><h1>{q.data?.naziv||'Agencija'}</h1><p>{q.data?.opis||'Profesionalna podrška pri pronalasku nekretnine.'}</p><small>{q.data?.grad||'Bosna i Hercegovina'}{q.data?.telefon?` · ${q.data.telefon}`:''}</small></div></div><section className="section"><div className="section-heading"><div><span className="kicker">Aktuelna ponuda</span><h2>Oglasi agencije</h2></div></div>{q.data?.oglasi?.length?<div className="card-grid">{q.data.oglasi.map((x:Nekretnina)=><PropertyCard item={x} key={x.id}/>)}</div>:<Empty icon={<Building2/>} title="Trenutno nema aktivnih oglasa" text="Novi oglasi ove agencije pojavit će se ovdje."/>}</section></div>}

function Workspace({title,description,action,children}:{title:string;description:string;action?:React.ReactNode;children:React.ReactNode}){return <div className="container page workspace"><div className="page-heading"><div><span className="kicker">Vaš Domus</span><h1>{title}</h1><p>{description}</p></div>{action}</div>{children}</div>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="empty-state">{icon}<h2>{title}</h2><p>{text}</p><Link className="button secondary" to="/nekretnine">Istraži nekretnine</Link></div>}
function DataCards<T>({items,empty,render}:{items:T[];empty:string;render:(x:T)=>React.ReactNode}){if(!items.length)return <Empty icon={<HandCoins/>} title={empty} text="Nove aktivnosti će se pojaviti ovdje."/>;return <div className="data-grid">{items.map((x:any)=><article className="data-card" key={x.id}>{render(x)}</article>)}</div>}
