const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  return sequelize.define('Nekretnina', {
    id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
    tip_nekretnine: { type: DataTypes.STRING, allowNull: false },
    naziv: { type: DataTypes.STRING, allowNull: false },
    kvadratura: { type: DataTypes.INTEGER, allowNull: false },
    cijena: { type: DataTypes.DECIMAL, allowNull: false },
    tip_grijanja: { type: DataTypes.STRING, allowNull: true },
    lokacija: { type: DataTypes.STRING, allowNull: false },
    godina_izgradnje: { type: DataTypes.INTEGER, allowNull: true },
    datum_objave: { type: DataTypes.DATEONLY, allowNull: false },
    opis: { type: DataTypes.TEXT, allowNull: true },
    kupljeno: { type: DataTypes.BOOLEAN, defaultValue: false },
    datumKupovine: { type: DataTypes.DATE, allowNull: true },
    prodajnaCijena: { type: DataTypes.DECIMAL, allowNull: true },
    kupacId: { type: DataTypes.INTEGER, allowNull: true },
    slug: { type: DataTypes.STRING(180), allowNull: true, unique: true },
    namjena: { type: DataTypes.ENUM('PRODAJA', 'NAJAM'), defaultValue: 'PRODAJA' },
    status: { type: DataTypes.ENUM('DRAFT', 'PENDING_REVIEW', 'CHANGES_REQUESTED', 'PUBLISHED', 'REJECTED', 'ARCHIVED', 'SOLD', 'RENTED'), defaultValue: 'PUBLISHED' },
    grad: { type: DataTypes.STRING(100), allowNull: true },
    naselje: { type: DataTypes.STRING(100), allowNull: true },
    punaAdresa: { type: DataTypes.STRING(255), allowNull: true },
    latPriblizno: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
    lngPriblizno: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
    latTacno: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
    lngTacno: { type: DataTypes.DECIMAL(10, 7), allowNull: true },
    brojSoba: { type: DataTypes.INTEGER, allowNull: true },
    brojKupatila: { type: DataTypes.INTEGER, allowNull: true },
    sprat: { type: DataTypes.INTEGER, allowNull: true },
    brojSpratova: { type: DataTypes.INTEGER, allowNull: true },
    parking: { type: DataTypes.BOOLEAN, defaultValue: false },
    balkon: { type: DataTypes.BOOLEAN, defaultValue: false },
    lift: { type: DataTypes.BOOLEAN, defaultValue: false },
    namjestenost: { type: DataTypes.STRING(50), allowNull: true },
    stanje: { type: DataTypes.STRING(80), allowNull: true },
    energetskaKlasa: { type: DataTypes.STRING(10), allowNull: true },
    dostupnoOd: { type: DataTypes.DATEONLY, allowNull: true },
    pogodnosti: { type: DataTypes.JSON, allowNull: true },
    ObjavljenaRevizijaId: { type: DataTypes.INTEGER, allowNull: true },
    AktivnaDraftRevizijaId: { type: DataTypes.INTEGER, allowNull: true },
  }, {
    freezeTableName: true,
    tableName: 'nekretnina',
  });
};
