import { MessageCircle, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { api } from '../lib/api';
import { disableProductAnalytics, enableProductAnalytics, track } from '../lib/observability';
import { useAuth } from '../auth/AuthContext';

export function BetaTools(){const {user}=useAuth(),location=useLocation();const [open,setOpen]=useState(false),[sent,setSent]=useState(false),[consent,setConsent]=useState(()=>localStorage.getItem('domus.analytics-consent'));
 useEffect(()=>{if(consent==='yes'){enableProductAnalytics();track('page_view',{path:location.pathname})}},[consent,location.pathname]);
 const choose=(value:'yes'|'no')=>{localStorage.setItem('domus.analytics-consent',value);setConsent(value);if(value==='yes')enableProductAnalytics();else disableProductAnalytics()};
 return <>{consent===null&&<div className="consent-banner"><div><strong>Pomozite nam poboljšati Domus</strong><p>Uz vašu saglasnost mjerimo samo korištenje funkcija. Privatne poruke, adrese i ponude se ne šalju.</p></div><button className="button small" onClick={()=>choose('yes')}>Dozvoli analitiku</button><button className="button ghost small" onClick={()=>choose('no')}>Samo nužno</button></div>}{user&&<button className="feedback-trigger" onClick={()=>{setOpen(true);setSent(false)}}><MessageCircle/> Beta feedback</button>}{open&&<div className="dialog-backdrop"><div className="dialog"><button className="dialog-close" onClick={()=>setOpen(false)} aria-label="Zatvori"><X/></button>{sent?<div className="action-success"><MessageCircle/><h2>Hvala na povratnoj informaciji</h2><p>Vaša prijava je evidentirana bez privatnog sadržaja.</p></div>:<><span className="kicker">Privatna beta</span><h2>Šta možemo poboljšati?</h2><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/api/v2/beta-feedback',{method:'POST',body:JSON.stringify({kategorija:f.get('kategorija'),ocjena:Number(f.get('ocjena')),poruka:f.get('poruka'),putanja:location.pathname})});track('beta_feedback_submitted',{category:String(f.get('kategorija'))});setSent(true)}}><label>Oblast<select name="kategorija"><option value="UX">Korištenje stranice</option><option value="SEARCH">Pretraga</option><option value="LISTING">Objavljivanje oglasa</option><option value="COMMUNICATION">Komunikacija</option><option value="BUG">Greška</option><option value="OTHER">Ostalo</option></select></label><label>Ocjena iskustva<select name="ocjena"><option value="5">5 — Odlično</option><option value="4">4 — Dobro</option><option value="3">3 — Osrednje</option><option value="2">2 — Loše</option><option value="1">1 — Vrlo loše</option></select></label><label>Opišite prijedlog ili problem<textarea name="poruka" minLength={5} maxLength={1500} rows={5} required/></label><button className="button">Pošalji</button></form></>}</div></div>}</>
}
