const crypto = require('crypto');
const fs = require('fs/promises');
const path = require('path');
const { Op, literal, QueryTypes } = require('sequelize');
const {
  sequelize, Korisnik, Nekretnina, SlikaNekretnine, OglasRevizija, ActivityEvent,
  OmiljenaNekretnina, Razgovor, Poruka, TerminPregleda, HistorijaTermina,
  Pregovor, StavkaPregovora, JavniFaq, Organizacija, ClanstvoOrganizacije,
  PozivOrganizacije, DokumentVerifikacije, BetaFeedback, AdminAuditLog,
  HistorijaCijene, Vodic,
} = require('../models');
const config = require('../config/env');
const { processImage, removeImageFiles } = require('../utils/imageVariants');
const { uploadsDir } = require('../middleware/upload');
const { sendSecurityEmail } = require('../utils/mailer');
const { privateUploadsDir } = require('../middleware/privateUpload');

const ok=(res,data,meta)=>res.json(meta?{data,meta}:{data});
const clean=(v,n=2000)=>String(v??'').trim().slice(0,n);
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const listingFields=['tip_nekretnine','naziv','kvadratura','cijena','tip_grijanja','lokacija','godina_izgradnje','opis','namjena','grad','naselje','punaAdresa','latTacno','lngTacno','brojSoba','brojKupatila','sprat','brojSpratova','parking','balkon','lift','namjestenost','stanje','energetskaKlasa','dostupnoOd','pogodnosti','OrganizacijaId','DodijeljeniAgentId'];

function sanitizeListing(input,base={}){const out={...base};for(const key of listingFields)if(input[key]!==undefined)out[key]=typeof input[key]==='string'?clean(input[key],key==='opis'?5000:500):input[key];for(const key of ['kvadratura','cijena','godina_izgradnje','brojSoba','brojKupatila','sprat','brojSpratova','OrganizacijaId','DodijeljeniAgentId'])if(out[key]!==undefined&&out[key]!==null&&out[key]!=='')out[key]=Number(out[key]);for(const key of ['parking','balkon','lift'])if(out[key]!==undefined)out[key]=!!out[key];return out}
function slugify(v){return clean(v||'oglas',180).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function approximate(value,id,axis){if(!Number.isFinite(Number(value)))return null;const seed=((Number(id)*37+(axis==='lat'?11:23))%7-3)*0.0007;return (Math.round(Number(value)*100)/100+seed).toFixed(7)}
function validationErrors(data){const e={};if(clean(data.naziv).length<8)e.naziv='Naziv mora imati najmanje 8 znakova.';if(!clean(data.tip_nekretnine))e.tip_nekretnine='Odaberite tip.';if(!['PRODAJA','NAJAM'].includes(data.namjena))e.namjena='Odaberite namjenu.';if(!(Number(data.kvadratura)>0))e.kvadratura='Unesite površinu.';if(!(Number(data.cijena)>0))e.cijena='Unesite cijenu.';if(!clean(data.lokacija))e.lokacija='Unesite lokaciju.';if(clean(data.opis).length<40)e.opis='Opis mora imati najmanje 40 znakova.';return e}
async function membership(userId,organizationId){if(!organizationId)return null;return ClanstvoOrganizacije.findOne({where:{KorisnikId:userId,OrganizacijaId:organizationId,status:'ACTIVE'}})}
async function canManageListing(user,listing){if(user.systemRole==='SUPER_ADMIN'||listing.KorisnikId===user.id)return true;const m=await membership(user.id,listing.OrganizacijaId);return !!m&&(m.uloga!=='AGENT'||listing.DodijeljeniAgentId===user.id)}
async function assertListing(req,res){const listing=await Nekretnina.findByPk(req.params.id);if(!listing)return res.status(404).json({error:{code:'NOT_FOUND',message:'Oglas nije pronađen.',requestId:req.requestId}}),null;if(!await canManageListing(req.korisnik,listing))return res.status(403).json({error:{code:'FORBIDDEN',message:'Nemate pravo upravljati ovim oglasom.',requestId:req.requestId}}),null;return listing}
async function hasPublishingAccess(user,organizationId){if(!config.beta.publishingRequired||user.systemRole==='SUPER_ADMIN')return true;if(user.betaPublishingEnabledAt)return true;if(organizationId){const org=await Organizacija.findByPk(organizationId);const m=await membership(user.id,organizationId);return !!(org?.betaPublishingEnabledAt&&m)}return false}
async function event(tip,userId,entitetTip,entitetId,metadata={}){await ActivityEvent.create({tip,ActorId:userId,entitetTip,entitetId,metadata}).catch(()=>{})}
async function clonePublishedImages(listingId,revisionId){
  const sources=await SlikaNekretnine.findAll({where:{NekretninaId:listingId,objavljena:true},order:[['redoslijed','ASC']]});
  const created=[];
  try{
    for(const source of sources){
      const stem=crypto.randomUUID(),extension=path.extname(source.filename)||'.jpg';
      const files=[['url',`${stem}${extension}`],['thumbnailUrl',`${stem}-thumbnail.webp`],['mediumUrl',`${stem}-medium.webp`],['largeUrl',`${stem}-large.webp`]];
      const urls={};
      for(const [field,filename] of files){if(!source[field])continue;await fs.copyFile(path.join(uploadsDir,path.basename(source[field])),path.join(uploadsDir,filename));created.push(filename);urls[field]=`/uploads/nekretnine/${filename}`}
      await SlikaNekretnine.create({...urls,filename:`${stem}${extension}`,originalName:source.originalName,mimeType:source.mimeType,velicina:source.velicina,sirina:source.sirina,visina:source.visina,glavna:source.glavna,redoslijed:source.redoslijed,objavljena:false,NekretninaId:listingId,OglasRevizijaId:revisionId});
    }
  }catch(error){await Promise.all(created.map(filename=>fs.unlink(path.join(uploadsDir,filename)).catch(()=>{})));throw error}
}

exports.myListings=async(req,res,next)=>{try{const rows=await Nekretnina.findAll({where:{[Op.or]:[{KorisnikId:req.korisnik.id},{DodijeljeniAgentId:req.korisnik.id}]},include:[{model:SlikaNekretnine,as:'Slike',separate:true,limit:1,order:[['glavna','DESC'],['redoslijed','ASC']]}],order:[['updatedAt','DESC']]});ok(res,rows)}catch(e){next(e)}};
exports.createDraft=async(req,res,next)=>{try{if(!req.korisnik.emailVerifiedAt)return res.status(403).json({error:{code:'EMAIL_NOT_VERIFIED',message:'Potvrdite email prije kreiranja oglasa.',requestId:req.requestId}});const orgId=req.body.OrganizacijaId?Number(req.body.OrganizacijaId):null;if(orgId&&!await membership(req.korisnik.id,orgId))return res.status(403).json({error:{code:'FORBIDDEN',message:'Niste član odabrane organizacije.',requestId:req.requestId}});let listing,revision;await sequelize.transaction(async transaction=>{listing=await Nekretnina.create({tip_nekretnine:'Stan',naziv:'Novi oglas',kvadratura:1,cijena:1,lokacija:'Nije uneseno',datum_objave:new Date(),opis:'',namjena:'PRODAJA',status:'DRAFT',KorisnikId:req.korisnik.id,OrganizacijaId:orgId,slug:`draft-${req.korisnik.id}-${Date.now().toString(36)}`},{transaction});revision=await OglasRevizija.create({NekretninaId:listing.id,AutorId:req.korisnik.id,podaci:sanitizeListing(req.body,{namjena:'PRODAJA',tip_nekretnine:'Stan'}),status:'DRAFT',verzija:1,dovrseniKorak:0},{transaction});await listing.update({AktivnaDraftRevizijaId:revision.id},{transaction})});await event('LISTING_DRAFT_CREATED',req.korisnik.id,'NEKRETNINA',listing.id);res.status(201);ok(res,{id:listing.id,slug:listing.slug,revisionId:revision.id,verzija:revision.verzija})}catch(e){next(e)}};
exports.editor=async(req,res,next)=>{try{const listing=await assertListing(req,res);if(!listing)return;let draft=listing.AktivnaDraftRevizijaId?await OglasRevizija.findByPk(listing.AktivnaDraftRevizijaId):null;if(!draft||!['DRAFT','CHANGES_REQUESTED'].includes(draft.status)){const base=listing.ObjavljenaRevizijaId?await OglasRevizija.findByPk(listing.ObjavljenaRevizijaId):null;draft=await OglasRevizija.create({NekretninaId:listing.id,AutorId:req.korisnik.id,podaci:base?.podaci||sanitizeListing(listing.toJSON()),status:'DRAFT',verzija:1,BaznaRevizijaId:base?.id||null});await clonePublishedImages(listing.id,draft.id);await listing.update({AktivnaDraftRevizijaId:draft.id})}const [images,history]=await Promise.all([SlikaNekretnine.findAll({where:{NekretninaId:listing.id,[Op.or]:[{OglasRevizijaId:draft.id},{OglasRevizijaId:null}]},order:[['redoslijed','ASC']]}),OglasRevizija.findAll({where:{NekretninaId:listing.id},attributes:['id','status','verzija','razlogOdluke','dovrseniKorak','createdAt','updatedAt'],order:[['createdAt','DESC']]})]);ok(res,{listing:{id:listing.id,slug:listing.slug,status:listing.status,ObjavljenaRevizijaId:listing.ObjavljenaRevizijaId},draft,images,history,publishingAllowed:await hasPublishingAccess(req.korisnik,listing.OrganizacijaId)})}catch(e){next(e)}};
exports.saveDraft=async(req,res,next)=>{try{const listing=await assertListing(req,res);if(!listing)return;const draft=await OglasRevizija.findByPk(listing.AktivnaDraftRevizijaId);if(!draft||!['DRAFT','CHANGES_REQUESTED'].includes(draft.status))return res.status(409).json({error:{code:'DRAFT_LOCKED',message:'Ova revizija više nije dostupna za uređivanje.',requestId:req.requestId}});const expected=Number(req.get('If-Match')||req.body.verzija);if(!expected||expected!==draft.verzija)return res.status(409).json({error:{code:'VERSION_CONFLICT',message:'Draft je u međuvremenu izmijenjen. Učitajte noviju verziju.',requestId:req.requestId}});const data=sanitizeListing(req.body.podaci||req.body,draft.podaci||{}),step=Math.min(5,Math.max(draft.dovrseniKorak||0,Number(req.body.dovrseniKorak)||0));const [count]=await OglasRevizija.update({podaci:data,dovrseniKorak:step,verzija:draft.verzija+1,status:'DRAFT',razlogOdluke:null},{where:{id:draft.id,verzija:expected}});if(!count)return res.status(409).json({error:{code:'VERSION_CONFLICT',message:'Draft je izmijenjen na drugom uređaju.',requestId:req.requestId}});ok(res,{id:draft.id,verzija:expected+1,savedAt:new Date().toISOString()})}catch(e){next(e)}};
exports.submitDraft=async(req,res,next)=>{try{const listing=await assertListing(req,res);if(!listing)return;if(!await hasPublishingAccess(req.korisnik,listing.OrganizacijaId))return res.status(403).json({error:{code:'BETA_ACCESS_REQUIRED',message:'Objavljivanje je trenutno dostupno odobrenim beta partnerima.',requestId:req.requestId}});const ownerScope=listing.OrganizacijaId?{OrganizacijaId:listing.OrganizacijaId}:{KorisnikId:req.korisnik.id,OrganizacijaId:null};const active=await Nekretnina.count({where:{...ownerScope,status:{[Op.in]:['PUBLISHED','PENDING_REVIEW']},id:{[Op.ne]:listing.id}}});if(active>=config.beta.maxPublishedPerOwner)return res.status(400).json({error:{code:'BETA_LISTING_LIMIT',message:'Dostigli ste trenutni beta limit aktivnih oglasa.',requestId:req.requestId}});const draft=await OglasRevizija.findByPk(listing.AktivnaDraftRevizijaId);if(!draft||!['DRAFT','CHANGES_REQUESTED'].includes(draft.status))return res.status(409).json({error:{code:'DRAFT_LOCKED',message:'Draft nije dostupan.',requestId:req.requestId}});const fieldErrors=validationErrors(draft.podaci||{});const imageCount=await SlikaNekretnine.count({where:{NekretninaId:listing.id,OglasRevizijaId:draft.id}});if(!imageCount)fieldErrors.fotografije='Dodajte najmanje jednu fotografiju.';if(Object.keys(fieldErrors).length)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Dovršite obavezna polja.',fieldErrors,requestId:req.requestId}});await sequelize.transaction(async transaction=>{await draft.update({status:'PENDING_REVIEW',zakljucanaAt:new Date(),dovrseniKorak:5},{transaction});await listing.update({status:listing.ObjavljenaRevizijaId?'PUBLISHED':'PENDING_REVIEW'},{transaction})});await event('LISTING_SUBMITTED',req.korisnik.id,'NEKRETNINA',listing.id,{revisionId:draft.id});res.status(202);ok(res,{id:listing.id,revisionId:draft.id,status:'PENDING_REVIEW'})}catch(e){next(e)}};
exports.listingStats=async(req,res,next)=>{try{const listing=await assertListing(req,res);if(!listing)return;const id=listing.id;const [views,favorites,conversations,appointments,offers,firstResponse]=await Promise.all([ActivityEvent.count({where:{tip:'LISTING_VIEWED',entitetTip:'NEKRETNINA',entitetId:id}}),OmiljenaNekretnina.count({where:{NekretninaId:id}}),Razgovor.count({where:{NekretninaId:id}}),TerminPregleda.count({where:{NekretninaId:id}}),Pregovor.count({where:{NekretninaId:id}}),sequelize.query('SELECT AVG(TIMESTAMPDIFF(SECOND, r.createdAt, p.createdAt)) prosjek FROM razgovor r JOIN poruka_v2 p ON p.RazgovorId=r.id AND p.PosiljalacId=r.VlasnikId WHERE r.NekretninaId=:id',{replacements:{id},type:QueryTypes.SELECT})]);ok(res,{views,favorites,conversations,appointments,offers,medianFirstResponseSeconds:Math.round(Number(firstResponse?.[0]?.prosjek)||0)})}catch(e){next(e)}};

exports.uploadDraftImage=async(req,res,next)=>{try{const listing=await assertListing(req,res);if(!listing){if(req.file)await fs.unlink(path.join(uploadsDir,req.file.filename)).catch(()=>{});return}if(!req.file)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Fotografija je obavezna.',requestId:req.requestId}});const draft=await OglasRevizija.findByPk(listing.AktivnaDraftRevizijaId);if(!draft||draft.status!=='DRAFT')throw Object.assign(new Error('Draft nije dostupan.'),{status:409,code:'DRAFT_LOCKED'});const count=await SlikaNekretnine.count({where:{NekretninaId:listing.id,OglasRevizijaId:draft.id}});if(count>=12)throw Object.assign(new Error('Oglas može imati najviše 12 fotografija.'),{status:400});const variants=await processImage(req.file.filename);const image=await SlikaNekretnine.create({url:`/uploads/nekretnine/${req.file.filename}`,filename:req.file.filename,originalName:path.basename(req.file.originalname).slice(0,255),mimeType:req.file.mimetype,velicina:req.file.size,...variants,glavna:count===0,redoslijed:count,objavljena:false,NekretninaId:listing.id,OglasRevizijaId:draft.id});res.status(201);ok(res,image)}catch(e){if(req.file)await Promise.all([req.file.filename,...['thumbnail','medium','large'].map(x=>`${path.parse(req.file.filename).name}-${x}.webp`)].map(f=>fs.unlink(path.join(uploadsDir,f)).catch(()=>{})));next(e)}};
exports.arrangeImages=async(req,res,next)=>{try{const listing=await assertListing(req,res);if(!listing)return;const draft=await OglasRevizija.findByPk(listing.AktivnaDraftRevizijaId);if(!draft||draft.status!=='DRAFT')return res.status(409).json({error:{code:'DRAFT_LOCKED',message:'Fotografije su zaključane.',requestId:req.requestId}});const ids=(req.body.ids||[]).map(Number),coverId=Number(req.body.coverId);const rows=await SlikaNekretnine.findAll({where:{id:{[Op.in]:ids},NekretninaId:listing.id,OglasRevizijaId:draft.id}});if(rows.length!==ids.length||!ids.includes(coverId))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Raspored fotografija nije važeći.',requestId:req.requestId}});await sequelize.transaction(async transaction=>{for(const row of rows)await row.update({redoslijed:ids.indexOf(row.id),glavna:row.id===coverId},{transaction})});ok(res,{ids,coverId})}catch(e){next(e)}};
exports.removeDraftImage=async(req,res,next)=>{try{const listing=await assertListing(req,res);if(!listing)return;const image=await SlikaNekretnine.findOne({where:{id:req.params.imageId,NekretninaId:listing.id,OglasRevizijaId:listing.AktivnaDraftRevizijaId}});if(!image)return res.status(404).json({error:{code:'NOT_FOUND',message:'Fotografija nije pronađena.',requestId:req.requestId}});await image.destroy();await removeImageFiles(image);res.status(204).end()}catch(e){next(e)}};

exports.feedback=async(req,res,next)=>{try{const kategorija=String(req.body.kategorija||'OTHER').toUpperCase(),poruka=clean(req.body.poruka,1500),putanja=clean(req.body.putanja,255);if(!['BUG','UX','SEARCH','LISTING','COMMUNICATION','OTHER'].includes(kategorija)||poruka.length<5||!putanja.startsWith('/'))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Povratna informacija nije potpuna.',requestId:req.requestId}});const row=await BetaFeedback.create({kategorija,poruka,putanja,ocjena:req.body.ocjena?Math.min(5,Math.max(1,Number(req.body.ocjena))):null,KorisnikId:req.korisnik?.id||null,NekretninaId:req.body.NekretninaId||null});res.status(201);ok(res,{id:row.id})}catch(e){next(e)}};
exports.adminBetaAccess=async(req,res,next)=>{try{const kind=req.params.kind,id=Number(req.params.id),enabled=!!req.body.enabled,reason=clean(req.body.reason,500);if(reason.length<5)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Razlog je obavezan.',requestId:req.requestId}});const model=kind==='organizacije'?Organizacija:Korisnik,entity=await model.findByPk(id);if(!entity)return res.status(404).json({error:{code:'NOT_FOUND',message:'Zapis nije pronađen.',requestId:req.requestId}});await entity.update({betaPublishingEnabledAt:enabled?new Date():null,betaPublishingGrantedBy:req.korisnik.id,betaPublishingReason:reason});await AdminAuditLog.create({AdminId:req.korisnik.id,akcija:enabled?'BETA_ACCESS_GRANTED':'BETA_ACCESS_REVOKED',entitetTip:kind==='organizacije'?'ORGANIZACIJA':'KORISNIK',entitetId:id,razlog:reason});ok(res,{id,enabled,betaPublishingEnabledAt:entity.betaPublishingEnabledAt})}catch(e){next(e)}};

async function requireOrgRole(req,res,roles){const m=await membership(req.korisnik.id,Number(req.params.id));if(!m||!roles.includes(m.uloga)){res.status(403).json({error:{code:'FORBIDDEN',message:'Nemate ovlaštenje za ovu organizaciju.',requestId:req.requestId}});return null}return m}
exports.myOrganizations=async(req,res,next)=>{try{const memberships=await ClanstvoOrganizacije.findAll({where:{KorisnikId:req.korisnik.id,status:'ACTIVE'},include:[{model:Organizacija,attributes:['id','naziv','slug','opis','grad','status','razlogOdluke','betaPublishingEnabledAt']}],order:[['createdAt','ASC']]});ok(res,memberships.map(x=>({...x.Organizacija.toJSON(),uloga:x.uloga,membershipId:x.id})))}catch(e){next(e)}};
exports.orgMembers=async(req,res,next)=>{try{if(!await requireOrgRole(req,res,['OWNER','MANAGER','AGENT']))return;const rows=await ClanstvoOrganizacije.findAll({where:{OrganizacijaId:req.params.id,status:'ACTIVE'},include:[{model:Korisnik,attributes:['id','ime','prezime','username','email']}],order:[['uloga','ASC'],['createdAt','ASC']]});ok(res,rows)}catch(e){next(e)}};
exports.inviteMember=async(req,res,next)=>{try{if(!await requireOrgRole(req,res,['OWNER','MANAGER']))return;const email=clean(req.body.email,255).toLowerCase(),uloga=String(req.body.uloga||'AGENT').toUpperCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!['OWNER','MANAGER','AGENT'].includes(uloga))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Poziv nije važeći.',requestId:req.requestId}});const token=crypto.randomBytes(32).toString('hex'),row=await PozivOrganizacije.create({email,uloga,tokenHash:hash(token),isticeAt:new Date(Date.now()+7*86400000),OrganizacijaId:req.params.id,PozvaoId:req.korisnik.id,status:'PENDING'});await sendSecurityEmail({to:email,subject:'Poziv u Domus agenciju',text:`Prihvatite poziv: ${config.appUrl}/organizacija/poziv?token=${token}`});res.status(201);ok(res,{id:row.id,email,uloga,isticeAt:row.isticeAt})}catch(e){next(e)}};
exports.acceptInvite=async(req,res,next)=>{try{const invitation=await PozivOrganizacije.findOne({where:{tokenHash:hash(clean(req.body.token,200)),status:'PENDING',isticeAt:{[Op.gt]:new Date()}}});if(!invitation||invitation.email.toLowerCase()!==String(req.korisnik.email||'').toLowerCase())return res.status(400).json({error:{code:'INVALID_INVITE',message:'Poziv nije važeći za ovaj nalog.',requestId:req.requestId}});await sequelize.transaction(async transaction=>{await ClanstvoOrganizacije.upsert({OrganizacijaId:invitation.OrganizacijaId,KorisnikId:req.korisnik.id,uloga:invitation.uloga,status:'ACTIVE'},{transaction});await invitation.update({status:'ACCEPTED',PrihvatioId:req.korisnik.id},{transaction})});ok(res,{OrganizacijaId:invitation.OrganizacijaId})}catch(e){next(e)}};
exports.updateMember=async(req,res,next)=>{try{const actor=await requireOrgRole(req,res,['OWNER','MANAGER']);if(!actor)return;const target=await ClanstvoOrganizacije.findOne({where:{id:req.params.memberId,OrganizacijaId:req.params.id,status:'ACTIVE'}});if(!target)return res.status(404).json({error:{code:'NOT_FOUND',message:'Član nije pronađen.',requestId:req.requestId}});const role=req.body.uloga&&String(req.body.uloga).toUpperCase();if(actor.uloga!=='OWNER'&&(target.uloga==='OWNER'||role==='OWNER'))return res.status(403).json({error:{code:'FORBIDDEN',message:'Samo owner upravlja owner ulogom.',requestId:req.requestId}});if(req.body.akcija==='REMOVE'){if(target.uloga==='OWNER'&&await ClanstvoOrganizacije.count({where:{OrganizacijaId:req.params.id,uloga:'OWNER',status:'ACTIVE'}})<=1)return res.status(400).json({error:{code:'LAST_OWNER',message:'Posljednji owner ne može biti uklonjen.',requestId:req.requestId}});await target.update({status:'REVOKED'});await Nekretnina.update({DodijeljeniAgentId:null},{where:{OrganizacijaId:req.params.id,DodijeljeniAgentId:target.KorisnikId}})}else if(['OWNER','MANAGER','AGENT'].includes(role))await target.update({uloga:role});else return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Akcija nije dozvoljena.',requestId:req.requestId}});ok(res,target)}catch(e){next(e)}};
exports.orgAnalytics=async(req,res,next)=>{try{if(!await requireOrgRole(req,res,['OWNER','MANAGER']))return;const ids=(await Nekretnina.findAll({where:{OrganizacijaId:req.params.id},attributes:['id']})).map(x=>x.id);if(!ids.length)return ok(res,{oglasi:0,pregledi:0,razgovori:0,termini:0,pregovori:0});const [views,conversations,appointments,negotiations]=await Promise.all([ActivityEvent.count({where:{tip:'LISTING_VIEWED',entitetId:{[Op.in]:ids}}}),Razgovor.count({where:{NekretninaId:{[Op.in]:ids}}}),TerminPregleda.count({where:{NekretninaId:{[Op.in]:ids}}}),Pregovor.count({where:{NekretninaId:{[Op.in]:ids}}})]);ok(res,{oglasi:ids.length,pregledi:views,razgovori:conversations,termini:appointments,pregovori:negotiations})}catch(e){next(e)}};
exports.transferOwnership=async(req,res,next)=>{try{if(!await requireOrgRole(req,res,['OWNER']))return;const target=await ClanstvoOrganizacije.findOne({where:{OrganizacijaId:req.params.id,KorisnikId:req.body.KorisnikId,status:'ACTIVE'}});const current=await ClanstvoOrganizacije.findOne({where:{OrganizacijaId:req.params.id,KorisnikId:req.korisnik.id,status:'ACTIVE',uloga:'OWNER'}});if(!target||!current)return res.status(400).json({error:{code:'INVALID_TRANSFER',message:'Prijenos vlasništva nije moguć.',requestId:req.requestId}});await sequelize.transaction(async transaction=>{await target.update({uloga:'OWNER'},{transaction});if(req.body.zadrziOwner!==true)await current.update({uloga:'MANAGER'},{transaction})});await AdminAuditLog.create({AdminId:req.korisnik.id,akcija:'ORGANIZATION_OWNERSHIP_TRANSFERRED',entitetTip:'ORGANIZACIJA',entitetId:Number(req.params.id),razlog:'Prijenos vlasništva organizacije',metadata:{toUserId:target.KorisnikId}});ok(res,{ownerId:target.KorisnikId})}catch(e){next(e)}};
exports.assignListing=async(req,res,next)=>{try{if(!await requireOrgRole(req,res,['OWNER','MANAGER']))return;const listing=await Nekretnina.findOne({where:{id:req.params.listingId,OrganizacijaId:req.params.id}}),agent=await ClanstvoOrganizacije.findOne({where:{OrganizacijaId:req.params.id,KorisnikId:req.body.KorisnikId,status:'ACTIVE'}});if(!listing||!agent)return res.status(404).json({error:{code:'NOT_FOUND',message:'Oglas ili agent nije pronađen.',requestId:req.requestId}});await listing.update({DodijeljeniAgentId:agent.KorisnikId});await event('LISTING_AGENT_ASSIGNED',req.korisnik.id,'NEKRETNINA',listing.id,{agentId:agent.KorisnikId});ok(res,{id:listing.id,DodijeljeniAgentId:agent.KorisnikId})}catch(e){next(e)}};
exports.uploadVerificationDocument=async(req,res,next)=>{try{if(!await requireOrgRole(req,res,['OWNER'])){if(req.file)await fs.unlink(path.join(privateUploadsDir,req.file.filename)).catch(()=>{});return}if(!req.file)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Dokument je obavezan.',requestId:req.requestId}});const row=await DokumentVerifikacije.create({naziv:path.basename(req.file.originalname).slice(0,255),filename:req.file.filename,mimeType:req.file.mimetype,velicina:req.file.size,OrganizacijaId:req.params.id,PostavioId:req.korisnik.id,status:'SUBMITTED'});res.status(201);ok(res,{id:row.id,naziv:row.naziv,status:row.status})}catch(e){if(req.file)await fs.unlink(path.join(privateUploadsDir,req.file.filename)).catch(()=>{});next(e)}};
exports.verificationDocuments=async(req,res,next)=>{try{const isModerator=['MODERATOR','SUPER_ADMIN'].includes(req.korisnik.systemRole);if(!isModerator&&!await requireOrgRole(req,res,['OWNER']))return;ok(res,await DokumentVerifikacije.findAll({where:{OrganizacijaId:req.params.id},attributes:['id','naziv','mimeType','velicina','status','createdAt'],order:[['createdAt','DESC']]}))}catch(e){next(e)}};
exports.downloadVerificationDocument=async(req,res,next)=>{try{const doc=await DokumentVerifikacije.findByPk(req.params.documentId);if(!doc)return res.status(404).json({error:{code:'NOT_FOUND',message:'Dokument nije pronađen.',requestId:req.requestId}});const isModerator=['MODERATOR','SUPER_ADMIN'].includes(req.korisnik.systemRole),owner=isModerator?null:await membership(req.korisnik.id,doc.OrganizacijaId);if(!isModerator&&owner?.uloga!=='OWNER')return res.status(403).json({error:{code:'FORBIDDEN',message:'Dokument nije dostupan.',requestId:req.requestId}});await AdminAuditLog.create({AdminId:req.korisnik.id,akcija:'VERIFICATION_DOCUMENT_VIEWED',entitetTip:'DOKUMENT',entitetId:doc.id,razlog:isModerator?'Moderacijski pregled verifikacijskog dokumenta':'Owner pregled verifikacijskog dokumenta'});res.type(doc.mimeType);res.set('Content-Disposition',`attachment; filename="${path.basename(doc.naziv).replace(/["\r\n]/g,'')}"`);res.sendFile(path.join(privateUploadsDir,doc.filename))}catch(e){next(e)}};

exports.conversationStatus=async(req,res,next)=>{try{const row=await Razgovor.findOne({where:{id:req.params.id,[Op.or]:[{PokretacId:req.korisnik.id},{VlasnikId:req.korisnik.id}]}});if(!row)return res.status(404).json({error:{code:'NOT_FOUND',message:'Razgovor nije pronađen.',requestId:req.requestId}});const action=String(req.body.action||'').toUpperCase();if(action==='BLOCK')await row.update({status:'BLOCKED',BlokiraoId:req.korisnik.id});else if(action==='CLOSE')await row.update({status:'CLOSED',zatvorenAt:new Date()});else if(action==='REOPEN'){if(row.status==='BLOCKED'&&row.BlokiraoId!==req.korisnik.id)return res.status(403).json({error:{code:'FORBIDDEN',message:'Razgovor ne možete ponovo otvoriti.',requestId:req.requestId}});await row.update({status:'OPEN',zatvorenAt:null,BlokiraoId:null})}else return res.status(400).json({error:{code:'INVALID_ACTION',message:'Akcija nije dozvoljena.',requestId:req.requestId}});await event('CONVERSATION_STATUS_CHANGED',req.korisnik.id,'RAZGOVOR',row.id,{status:row.status});ok(res,row)}catch(e){next(e)}};
exports.markConversationRead=async(req,res,next)=>{try{const row=await Razgovor.findOne({where:{id:req.params.id,[Op.or]:[{PokretacId:req.korisnik.id},{VlasnikId:req.korisnik.id}]}});if(!row)return res.status(404).json({error:{code:'NOT_FOUND',message:'Razgovor nije pronađen.',requestId:req.requestId}});await Poruka.update({procitanoAt:new Date(),isporucenoAt:literal('COALESCE(isporucenoAt, NOW())')},{where:{RazgovorId:row.id,PosiljalacId:{[Op.ne]:req.korisnik.id},procitanoAt:null}});res.status(204).end()}catch(e){next(e)}};

exports.appointmentHistory=async(req,res,next)=>{try{const t=await TerminPregleda.findByPk(req.params.id);if(!t||![t.PodnosilacId,t.VlasnikId].includes(req.korisnik.id))return res.status(404).json({error:{code:'NOT_FOUND',message:'Termin nije pronađen.',requestId:req.requestId}});ok(res,await HistorijaTermina.findAll({where:{TerminPregledaId:t.id},order:[['createdAt','ASC']]}))}catch(e){next(e)}};
exports.updateAppointmentV2=async(req,res,next)=>{try{const t=await TerminPregleda.findByPk(req.params.id);if(!t||![t.PodnosilacId,t.VlasnikId].includes(req.korisnik.id))return res.status(404).json({error:{code:'NOT_FOUND',message:'Termin nije pronađen.',requestId:req.requestId}});const isOwner=t.VlasnikId===req.korisnik.id,nextStatus=String(req.body.status||'').toUpperCase(),transitions={PENDING:isOwner?['CONFIRMED','RESCHEDULED','DECLINED']:['CANCELLED'],RESCHEDULED:isOwner?['CONFIRMED','DECLINED']:['CANCELLED'],CONFIRMED:isOwner?['COMPLETED','RESCHEDULED']:['CANCELLED'],DECLINED:[],CANCELLED:[],COMPLETED:[]};if(!(transitions[t.status]||[]).includes(nextStatus))return res.status(409).json({error:{code:'INVALID_TRANSITION',message:`Promjena ${t.status} → ${nextStatus} nije dozvoljena.`,requestId:req.requestId}});const oldStatus=t.status,oldTime=t.predlozeniTermin,newTime=req.body.predlozeniTermin?new Date(req.body.predlozeniTermin):oldTime;if(nextStatus==='RESCHEDULED'&&(!req.body.predlozeniTermin||newTime<=new Date()))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Novi termin mora biti u budućnosti.',requestId:req.requestId}});await sequelize.transaction(async transaction=>{await t.update({status:nextStatus,predlozeniTermin:newTime,odgovor:clean(req.body.odgovor,500)||null},{transaction});await HistorijaTermina.create({TerminPregledaId:t.id,ActorId:req.korisnik.id,prethodniStatus:oldStatus,noviStatus:nextStatus,prethodniTermin:oldTime,noviTermin:newTime,napomena:clean(req.body.odgovor,500)||null},{transaction})});await event('APPOINTMENT_STATUS_CHANGED',req.korisnik.id,'TERMIN',t.id,{from:oldStatus,to:nextStatus});ok(res,t)}catch(e){next(e)}};
exports.negotiations=async(req,res,next)=>{try{ok(res,await Pregovor.findAll({where:{[Op.or]:[{PokretacId:req.korisnik.id},{PrimaocId:req.korisnik.id}]},include:[{model:Nekretnina,attributes:['id','naziv','slug']},{model:StavkaPregovora,as:'Stavke'}],order:[['updatedAt','DESC']]}))}catch(e){next(e)}};
exports.createNegotiation=async(req,res,next)=>{try{const listing=await Nekretnina.findOne({where:{id:req.body.NekretninaId,status:'PUBLISHED'}}),amount=Number(req.body.iznos);if(!listing||listing.KorisnikId===req.korisnik.id||!(amount>0))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Ponuda nije važeća.',requestId:req.requestId}});let negotiation,item;await sequelize.transaction(async transaction=>{negotiation=await Pregovor.create({NekretninaId:listing.id,PokretacId:req.korisnik.id,PrimaocId:listing.KorisnikId,status:'OPEN',isticeAt:new Date(Date.now()+7*86400000)},{transaction});item=await StavkaPregovora.create({PregovorId:negotiation.id,AutorId:req.korisnik.id,tip:'OFFER',iznos:amount,napomena:clean(req.body.napomena,1000)},{transaction})});res.status(201);ok(res,{...negotiation.toJSON(),Stavke:[item]})}catch(e){next(e)}};
exports.addNegotiationItem=async(req,res,next)=>{try{const p=await Pregovor.findOne({where:{id:req.params.id,[Op.or]:[{PokretacId:req.korisnik.id},{PrimaocId:req.korisnik.id}]}});if(!p||p.status!=='OPEN'||(p.isticeAt&&p.isticeAt<new Date()))return res.status(409).json({error:{code:'NEGOTIATION_CLOSED',message:'Pregovor nije aktivan.',requestId:req.requestId}});const tip=String(req.body.tip||'').toUpperCase(),amount=req.body.iznos==null?null:Number(req.body.iznos);if(!['COUNTER','ACCEPT','REJECT','WITHDRAW'].includes(tip)||(tip==='COUNTER'&&!(amount>0)))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Stavka pregovora nije važeća.',requestId:req.requestId}});const allowed=tip==='WITHDRAW'?req.korisnik.id===p.PokretacId:tip==='ACCEPT'||tip==='REJECT'?req.korisnik.id===p.PrimaocId:true;if(!allowed)return res.status(403).json({error:{code:'FORBIDDEN',message:'Akcija nije dozvoljena.',requestId:req.requestId}});let item;await sequelize.transaction(async transaction=>{item=await StavkaPregovora.create({PregovorId:p.id,AutorId:req.korisnik.id,tip,iznos:amount,napomena:clean(req.body.napomena,1000)},{transaction});const status={ACCEPT:'ACCEPTED',REJECT:'REJECTED',WITHDRAW:'WITHDRAWN'}[tip];if(status)await p.update({status},{transaction});else await p.update({isticeAt:new Date(Date.now()+7*86400000)},{transaction})});res.status(201);ok(res,item)}catch(e){next(e)}};

exports.updateFaq=async(req,res,next)=>{try{const faq=await JavniFaq.findByPk(req.params.id,{include:[Nekretnina]});if(!faq)return res.status(404).json({error:{code:'NOT_FOUND',message:'FAQ nije pronađen.',requestId:req.requestId}});const isModerator=['MODERATOR','SUPER_ADMIN'].includes(req.korisnik.systemRole),isOwner=faq.Nekretnina?.KorisnikId===req.korisnik.id;if(!isModerator&&!isOwner)return res.status(403).json({error:{code:'FORBIDDEN',message:'Nemate ovlaštenje.',requestId:req.requestId}});const values={};if(req.body.pitanje!==undefined)values.pitanje=clean(req.body.pitanje,500);if(req.body.odgovor!==undefined)values.odgovor=clean(req.body.odgovor,1500);if(req.body.status!==undefined&&['PUBLISHED','HIDDEN'].includes(req.body.status))values.status=req.body.status;values.uredjenoAt=new Date();await faq.update(values);ok(res,faq)}catch(e){next(e)}};

exports.compare=async(req,res,next)=>{try{const ids=String(req.query.ids||'').split(',').map(Number).filter(Boolean).slice(0,4);const rows=await Nekretnina.findAll({where:{id:{[Op.in]:ids},status:{[Op.in]:['PUBLISHED','SOLD','RENTED']}},attributes:{exclude:['punaAdresa','latTacno','lngTacno']},include:[{model:SlikaNekretnine,as:'Slike',where:{objavljena:true},required:false,separate:true,limit:1,order:[['glavna','DESC']]}]});ok(res,rows)}catch(e){next(e)}};
exports.recommendations=async(req,res,next)=>{try{const favorite=await OmiljenaNekretnina.findOne({where:{KorisnikId:req.korisnik.id},include:[Nekretnina],order:[['createdAt','DESC']]});if(!favorite?.Nekretnina)return ok(res,await Nekretnina.findAll({where:{status:'PUBLISHED'},attributes:{exclude:['punaAdresa','latTacno','lngTacno']},include:[{model:SlikaNekretnine,as:'Slike',where:{objavljena:true},required:false,separate:true,limit:1}],limit:6,order:[['datum_objave','DESC']]}));const ref=favorite.Nekretnina,price=Number(ref.cijena);const rows=await Nekretnina.findAll({where:{id:{[Op.ne]:ref.id},status:'PUBLISHED',[Op.or]:[{grad:ref.grad||null},{tip_nekretnine:ref.tip_nekretnine},{cijena:{[Op.between]:[price*.75,price*1.25]}}]},attributes:{exclude:['punaAdresa','latTacno','lngTacno']},include:[{model:SlikaNekretnine,as:'Slike',where:{objavljena:true},required:false,separate:true,limit:1}],limit:6,order:[['datum_objave','DESC']]});ok(res,rows)}catch(e){next(e)}};
exports.priceHistory=async(req,res,next)=>{try{const listing=await Nekretnina.findOne({where:{slug:req.params.slug,status:{[Op.in]:['PUBLISHED','SOLD','RENTED']}}});if(!listing)return res.status(404).json({error:{code:'NOT_FOUND',message:'Oglas nije pronađen.',requestId:req.requestId}});ok(res,await HistorijaCijene.findAll({where:{NekretninaId:listing.id},attributes:['staraCijena','novaCijena','razlog','createdAt'],order:[['createdAt','ASC']]}))}catch(e){next(e)}};
exports.guides=async(req,res,next)=>{try{ok(res,await Vodic.findAll({where:{status:'PUBLISHED'},attributes:['id','slug','naslov','sazetak','objavljenoAt'],order:[['objavljenoAt','DESC']]}))}catch(e){next(e)}};
exports.guide=async(req,res,next)=>{try{const row=await Vodic.findOne({where:{slug:req.params.slug,status:'PUBLISHED'},attributes:['id','slug','naslov','sazetak','sadrzaj','objavljenoAt']});if(!row)return res.status(404).json({error:{code:'NOT_FOUND',message:'Vodič nije pronađen.',requestId:req.requestId}});ok(res,row)}catch(e){next(e)}};

exports.adminBetaFeedback=async(req,res,next)=>{try{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(10,Number(req.query.limit)||25)),where={};if(req.query.status)where.status=req.query.status;if(req.query.kategorija)where.kategorija=req.query.kategorija;const result=await BetaFeedback.findAndCountAll({where,attributes:{exclude:['screenshotUrl']},limit,offset:(page-1)*limit,order:[['createdAt','DESC']]});ok(res,result.rows,{page,limit,total:result.count,totalPages:Math.ceil(result.count/limit)})}catch(e){next(e)}};
function paging(q){const page=Math.max(1,Number(q.page)||1),pageSize=Math.min(100,Math.max(10,Number(q.pageSize)||25));return{page,pageSize,limit:pageSize,offset:(page-1)*pageSize}}
exports.adminUsers=async(req,res,next)=>{try{const p=paging(req.query),where={};if(req.query.role)where.systemRole=req.query.role;if(req.query.status==='SUSPENDED')where.suspendedAt={[Op.ne]:null};if(req.query.status==='DELETED')where.deletedAt={[Op.ne]:null};if(req.query.search)where[Op.or]=['ime','prezime','username','email'].map(field=>({[field]:{[Op.like]:`%${clean(req.query.search,100)}%`}}));const result=await Korisnik.findAndCountAll({where,attributes:['id','ime','prezime','username','email','emailVerifiedAt','systemRole','suspendedAt','suspendedUntil','deletedAt','betaPublishingEnabledAt','updatedAt'],order:[['id','DESC']],limit:p.limit,offset:p.offset});ok(res,result.rows,{page:p.page,pageSize:p.pageSize,total:result.count,totalPages:Math.max(1,Math.ceil(result.count/p.pageSize))})}catch(e){next(e)}};
exports.adminActivity=async(req,res,next)=>{try{const p=paging(req.query),where={createdAt:{[Op.gte]:new Date(Date.now()-365*86400000)}};if(req.query.tip)where.tip=req.query.tip;if(req.query.actorId)where.ActorId=Number(req.query.actorId);const result=await ActivityEvent.findAndCountAll({where,include:[{model:Korisnik,as:'Actor',attributes:['id','username']}],attributes:['id','tip','entitetTip','entitetId','metadata','createdAt'],order:[['createdAt','DESC']],limit:p.limit,offset:p.offset});ok(res,result.rows,{page:p.page,pageSize:p.pageSize,total:result.count,totalPages:Math.max(1,Math.ceil(result.count/p.pageSize))})}catch(e){next(e)}};
exports.adminAnalytics=async(req,res,next)=>{try{const days=Math.min(365,Math.max(7,Number(req.query.period)||30)),since=new Date(Date.now()-days*86400000),previous=new Date(Date.now()-days*2*86400000);const [views,favorites,conversations,appointments,negotiations,published,previousViews,top,cities,workload,emptySearches]=await Promise.all([ActivityEvent.count({where:{tip:'LISTING_VIEWED',createdAt:{[Op.gte]:since}}}),OmiljenaNekretnina.count({where:{createdAt:{[Op.gte]:since}}}),Razgovor.count({where:{createdAt:{[Op.gte]:since}}}),TerminPregleda.count({where:{createdAt:{[Op.gte]:since}}}),Pregovor.count({where:{createdAt:{[Op.gte]:since}}}),Nekretnina.count({where:{status:'PUBLISHED'}}),ActivityEvent.count({where:{tip:'LISTING_VIEWED',createdAt:{[Op.between]:[previous,since]}}}),sequelize.query('SELECT n.id,n.naziv,n.slug,COUNT(a.id) pregledi FROM nekretnina n LEFT JOIN activity_event a ON a.entitetId=n.id AND a.tip="LISTING_VIEWED" AND a.createdAt>=:since WHERE n.status="PUBLISHED" GROUP BY n.id,n.naziv,n.slug ORDER BY pregledi DESC LIMIT 10',{replacements:{since},type:QueryTypes.SELECT}),Nekretnina.findAll({where:{status:'PUBLISHED'},attributes:['grad',[literal('COUNT(*)'),'broj']],group:['grad'],order:[[literal('broj'),'DESC']],limit:10}),OglasRevizija.count({where:{status:'PENDING_REVIEW'}}),ActivityEvent.count({where:{tip:'SEARCH_NO_RESULTS',createdAt:{[Op.gte]:since}}})]);ok(res,{period:days,kpi:{views,favorites,conversations,appointments,negotiations,published,emptySearches},comparison:{views:previousViews?Math.round((views-previousViews)/previousViews*100):null},funnel:{views,favorites,conversations,appointments,negotiations},topListings:top,cities,moderationWorkload:workload})}catch(e){next(e)}};
const csvCell=value=>`"${String(value??'').replace(/"/g,'""').replace(/[\r\n]+/g,' ')}"`;
exports.adminCsv=async(req,res,next)=>{try{const type=req.params.type,reason=clean(req.query.reason,500);if(reason.length<5)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Razlog izvoza je obavezan.',requestId:req.requestId}});let headers,rows;if(type==='korisnici'){headers=['id','username','email','uloga','status'];rows=(await Korisnik.findAll({attributes:['id','username','email','systemRole','suspendedAt','deletedAt'],limit:10000})).map(x=>[x.id,x.username,x.email,x.systemRole,x.deletedAt?'DELETED':x.suspendedAt?'SUSPENDED':'ACTIVE'])}else if(type==='oglasi'){headers=['id','naziv','grad','status','datum'];rows=(await Nekretnina.findAll({attributes:['id','naziv','grad','status','datum_objave'],limit:10000})).map(x=>[x.id,x.naziv,x.grad,x.status,x.datum_objave])}else if(type==='aktivnosti'){headers=['id','tip','entitet','entitetId','vrijeme'];rows=(await ActivityEvent.findAll({attributes:['id','tip','entitetTip','entitetId','createdAt'],limit:10000,order:[['createdAt','DESC']]})).map(x=>[x.id,x.tip,x.entitetTip,x.entitetId,x.createdAt.toISOString()])}else return res.status(404).json({error:{code:'NOT_FOUND',message:'Izvoz nije podržan.',requestId:req.requestId}});await AdminAuditLog.create({AdminId:req.korisnik.id,akcija:'CSV_EXPORTED',entitetTip:type.toUpperCase(),razlog,metadata:{rows:rows.length}});res.type('text/csv');res.set('Content-Disposition',`attachment; filename="domus-${type}.csv"`);res.send('\uFEFF'+[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\n'))}catch(e){next(e)}};
exports.adminGuides=async(req,res,next)=>{try{ok(res,await Vodic.findAll({attributes:['id','slug','naslov','sazetak','status','objavljenoAt','updatedAt'],order:[['updatedAt','DESC']]}))}catch(e){next(e)}};
exports.createGuide=async(req,res,next)=>{try{const naslov=clean(req.body.naslov,200),sazetak=clean(req.body.sazetak,500),sadrzaj=clean(req.body.sadrzaj,50000);if(naslov.length<5||sazetak.length<20||sadrzaj.length<100)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Naslov, sažetak i sadržaj nisu potpuni.',requestId:req.requestId}});const status=req.body.status==='PUBLISHED'?'PUBLISHED':'DRAFT',row=await Vodic.create({naslov,sazetak,sadrzaj,slug:`${slugify(naslov)}-${Date.now().toString(36)}`,status,objavljenoAt:status==='PUBLISHED'?new Date():null,AutorId:req.korisnik.id});res.status(201);ok(res,row)}catch(e){next(e)}};
exports.updateGuide=async(req,res,next)=>{try{const row=await Vodic.findByPk(req.params.id);if(!row)return res.status(404).json({error:{code:'NOT_FOUND',message:'Vodič nije pronađen.',requestId:req.requestId}});const values={};for(const key of ['naslov','sazetak','sadrzaj'])if(req.body[key]!==undefined)values[key]=clean(req.body[key],key==='sadrzaj'?50000:key==='sazetak'?500:200);if(['DRAFT','PUBLISHED'].includes(req.body.status)){values.status=req.body.status;if(req.body.status==='PUBLISHED'&&!row.objavljenoAt)values.objavljenoAt=new Date()}await row.update(values);ok(res,row)}catch(e){next(e)}};
exports.retention=async()=>{await ActivityEvent.destroy({where:{createdAt:{[Op.lt]:new Date(Date.now()-365*86400000)}}});await Pregovor.update({status:'EXPIRED'},{where:{status:'OPEN',isticeAt:{[Op.lt]:new Date()}}})};
