const crypto = require('crypto');
const bcrypt = require('bcrypt');
const { Op } = require('sequelize');
const { Korisnik, ActivityEvent } = require('../models');
const config = require('../config/env');
const { sendSecurityEmail } = require('../utils/mailer');

const hashToken = (token) => crypto.createHash('sha256').update(token).digest('hex');
const safeUser = (u) => ({ id:u.id, ime:u.ime, prezime:u.prezime, username:u.username, email:u.email, emailVerified:!!u.emailVerifiedAt, systemRole:u.systemRole || (u.admin?'SUPER_ADMIN':'USER'), betaPublishingEnabled:!!u.betaPublishingEnabledAt });
const regenerate = (req) => new Promise((resolve,reject)=>req.session.regenerate(e=>e?reject(e):resolve()));
function setSession(req,u){req.session.userId=u.id;req.session.username=u.username;req.session.admin=u.admin||u.systemRole==='SUPER_ADMIN';req.session.systemRole=u.systemRole||'USER';}
async function activity(tip,userId,metadata={}){await ActivityEvent.create({tip,ActorId:userId,metadata}).catch(()=>{});}

exports.session=async(req,res)=>{if(!req.session?.userId)return res.json({data:{korisnik:null}});const u=await Korisnik.findByPk(req.session.userId);if(!u||u.deletedAt)return res.json({data:{korisnik:null}});res.json({data:{korisnik:safeUser(u)}})};
exports.register=async(req,res,next)=>{try{const {ime,prezime,username,email,password}=req.body;if(!ime?.trim()||!prezime?.trim()||!username?.trim()||!email?.trim()||typeof password!=='string'||password.length<8)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Popunite sva polja; lozinka mora imati najmanje 8 znakova.'}});const cleanEmail=email.trim().toLowerCase();const existing=await Korisnik.findOne({where:{[Op.or]:[{username:username.trim()},{email:cleanEmail}]}});if(existing)return res.status(409).json({error:{code:'ACCOUNT_EXISTS',message:'Username ili email je već zauzet.'}});const token=crypto.randomBytes(32).toString('hex');const u=await Korisnik.create({ime:ime.trim(),prezime:prezime.trim(),username:username.trim(),email:cleanEmail,password:await bcrypt.hash(password,config.bcrypt.rounds),admin:false,systemRole:'USER',emailVerificationTokenHash:hashToken(token),emailVerificationExpiresAt:new Date(Date.now()+24*60*60*1000)});await regenerate(req);setSession(req,u);await activity('USER_REGISTERED',u.id);const link=`${config.appUrl}/api/v2/auth/verify-email?token=${token}`;await sendSecurityEmail({to:u.email,subject:'Potvrdite Domus email',text:`Potvrdite email otvaranjem linka: ${link}`});res.status(201).json({data:{korisnik:safeUser(u),verificationRequired:true}})}catch(e){next(e)}};
exports.login=async(req,res,next)=>{try{const identitet=(req.body.identitet||req.body.username||'').trim();const password=req.body.password;if(!identitet||!password)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Unesite identitet i lozinku.'}});const u=await Korisnik.findOne({where:{[Op.or]:[{username:identitet},{email:identitet.toLowerCase()}]}});if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:{code:'INVALID_CREDENTIALS',message:'Neispravni podaci za prijavu.'}});const suspended=u.suspendedAt&&(!u.suspendedUntil||new Date(u.suspendedUntil)>new Date());if(u.deletedAt||suspended)return res.status(403).json({error:{code:'ACCOUNT_INACTIVE',message:suspended?'Nalog je suspendovan.':'Nalog nije aktivan.'}});await regenerate(req);setSession(req,u);await activity('LOGIN_SUCCEEDED',u.id);res.json({data:{korisnik:safeUser(u)}})}catch(e){next(e)}};
exports.logout=(req,res)=>req.session.destroy(()=>{res.clearCookie('nekretnine.sid');res.status(204).end()});
exports.verifyEmail=async(req,res,next)=>{try{const hash=hashToken(String(req.query.token||req.body.token||''));const u=await Korisnik.findOne({where:{emailVerificationTokenHash:hash,emailVerificationExpiresAt:{[Op.gt]:new Date()}}});if(!u)return res.status(400).json({error:{code:'INVALID_TOKEN',message:'Link nije važeći ili je istekao.'}});await u.update({emailVerifiedAt:new Date(),emailVerificationTokenHash:null,emailVerificationExpiresAt:null});await activity('EMAIL_VERIFIED',u.id);res.redirect('/profil?verified=1')}catch(e){next(e)}};
exports.forgotPassword=async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase();const u=await Korisnik.findOne({where:{email}});if(u){const token=crypto.randomBytes(32).toString('hex');await u.update({passwordResetTokenHash:hashToken(token),passwordResetExpiresAt:new Date(Date.now()+60*60*1000)});await sendSecurityEmail({to:u.email,subject:'Reset Domus lozinke',text:`Otvorite ${config.appUrl}/reset-lozinke?token=${token}`});}res.json({data:{poruka:'Ako nalog postoji, poslali smo sigurnosni link.'}})}catch(e){next(e)}};
exports.resetPassword=async(req,res,next)=>{try{const u=await Korisnik.findOne({where:{passwordResetTokenHash:hashToken(String(req.body.token||'')),passwordResetExpiresAt:{[Op.gt]:new Date()}}});if(!u||typeof req.body.password!=='string'||req.body.password.length<8)return res.status(400).json({error:{code:'INVALID_TOKEN',message:'Zahtjev nije važeći.'}});await u.update({password:await bcrypt.hash(req.body.password,config.bcrypt.rounds),passwordResetTokenHash:null,passwordResetExpiresAt:null});await activity('PASSWORD_RESET',u.id);res.json({data:{poruka:'Lozinka je promijenjena.'}})}catch(e){next(e)}};
exports.setEmail=async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Unesite ispravnu email adresu.'}});const taken=await Korisnik.findOne({where:{email,id:{[Op.ne]:req.korisnik.id}}});if(taken)return res.status(409).json({error:{code:'EMAIL_EXISTS',message:'Email je već povezan s drugim nalogom.'}});const token=crypto.randomBytes(32).toString('hex');await req.korisnik.update({email,emailVerifiedAt:null,emailVerificationTokenHash:hashToken(token),emailVerificationExpiresAt:new Date(Date.now()+24*60*60*1000)});await sendSecurityEmail({to:email,subject:'Potvrdite Domus email',text:`Potvrdite email otvaranjem linka: ${config.appUrl}/api/v2/auth/verify-email?token=${token}`});await activity('EMAIL_VERIFICATION_REQUESTED',req.korisnik.id);res.json({data:{poruka:'Poslali smo link za potvrdu emaila.',korisnik:safeUser(req.korisnik)}})}catch(e){next(e)}};
