const { Op, fn, col, literal } = require('sequelize');
const {
  sequelize, Korisnik, Nekretnina, SlikaNekretnine, Organizacija, ClanstvoOrganizacije,
  Razgovor, Poruka, TerminPregleda, PregovarackaPonuda, JavniFaq, Obavijest,
  ActivityEvent, AdminAuditLog, PrijavaSadrzaja, OglasRevizija, OmiljenaNekretnina,
} = require('../models');
const hub = require('../utils/notificationHub');

const ok=(res,data,meta)=>res.json({data,...(meta?{meta}:{})});
const publicOwner={model:Korisnik,attributes:['id','ime','prezime','username']};
const images={model:SlikaNekretnine,as:'Slike',separate:true,order:[['glavna','DESC'],['redoslijed','ASC'],['id','ASC']]};
const publicPropertyAttrs={exclude:['punaAdresa','latTacno','lngTacno']};
const clean=(value,max=2000)=>String(value||'').trim().slice(0,max);
function requireVerified(req,res){if(!req.korisnik.email||!req.korisnik.emailVerifiedAt){res.status(403).json({error:{code:'EMAIL_NOT_VERIFIED',message:'Potvrdite email prije ove akcije.'}});return false}return true}
async function event(tip,actorId,entitetTip,entitetId,metadata={}){return ActivityEvent.create({tip,ActorId:actorId||null,entitetTip,entitetId,metadata}).catch(()=>null)}
async function notify(userId,tip,naslov,poruka,link){if(!userId)return;const n=await Obavijest.create({KorisnikId:userId,tip,naslov,poruka,link});hub.emit(`user:${userId}`,n.toJSON())}
const isOperator=(req,property)=>req.korisnik.systemRole==='SUPER_ADMIN'||req.korisnik.systemRole==='MODERATOR'||property.KorisnikId===req.korisnik.id;
async function findProperty(identifier,options={}){const where=/^\d+$/.test(identifier)?{id:Number(identifier)}:{slug:identifier};return Nekretnina.findOne({where,...options})}

exports.propertyDetail=async(req,res,next)=>{try{const item=await findProperty(req.params.slug,{attributes:publicPropertyAttrs,include:[images,publicOwner,{model:Organizacija,attributes:['id','naziv','slug','status']}]});if(!item)return res.status(404).json({error:{code:'NOT_FOUND',message:'Oglas nije pronađen.'}});const privileged=req.session?.userId===item.KorisnikId||['MODERATOR','SUPER_ADMIN'].includes(req.session?.systemRole);if(item.status!=='PUBLISHED'&&!['SOLD','RENTED','ARCHIVED'].includes(item.status)&&!privileged)return res.status(404).json({error:{code:'NOT_FOUND',message:'Oglas nije javno dostupan.'}});const json=item.toJSON();if(json.Organizacija)json.Organizacija.verificirana=json.Organizacija.status==='VERIFIED';await event('LISTING_VIEWED',req.session?.userId||null,'NEKRETNINA',item.id,{authenticated:!!req.session?.userId});ok(res,json)}catch(e){next(e)}};
exports.similar=async(req,res,next)=>{try{const item=await findProperty(req.params.slug);if(!item)return ok(res,[]);const price=Number(item.cijena);const rows=await Nekretnina.findAll({where:{id:{[Op.ne]:item.id},kupljeno:false,tip_nekretnine:item.tip_nekretnine,lokacija:item.lokacija,cijena:{[Op.between]:[price*.75,price*1.25]},status:{[Op.notIn]:['ARCHIVED','SOLD','RENTED','REJECTED']}},attributes:publicPropertyAttrs,include:[images],limit:3,order:[['datum_objave','DESC']]});ok(res,rows)}catch(e){next(e)}};
exports.faq=async(req,res,next)=>{try{ok(res,await JavniFaq.findAll({where:{NekretninaId:req.params.id,status:'PUBLISHED'},attributes:['id','pitanje','odgovor','createdAt'],order:[['id','DESC']]}))}catch(e){next(e)}};

exports.conversations=async(req,res,next)=>{try{const id=req.korisnik.id;const rows=await Razgovor.findAll({where:{[Op.or]:[{PokretacId:id},{VlasnikId:id}]},include:[{model:Nekretnina,attributes:['id','naziv','lokacija','slug']},{model:Korisnik,as:'Pokretac',attributes:['id','ime','prezime','username']},{model:Korisnik,as:'Vlasnik',attributes:['id','ime','prezime','username']},{model:Poruka,as:'Poruke',separate:true,limit:1,order:[['id','DESC']]}],order:[['zadnjaPorukaAt','DESC'],['updatedAt','DESC']]});ok(res,rows.map(r=>{const x=r.toJSON(),other=r.PokretacId===id?x.Vlasnik:x.Pokretac;return{id:x.id,status:x.status,Nekretnina:x.Nekretnina,drugaStrana:{id:other.id,naziv:`${other.ime} ${other.prezime}`},zadnjaPoruka:x.Poruke?.[0]?.tekst,neprocitano:0,updatedAt:x.zadnjaPorukaAt||x.updatedAt}}))}catch(e){next(e)}};
exports.createConversation=async(req,res,next)=>{try{if(!requireVerified(req,res))return;const tekst=clean(req.body.tekst);if(tekst.length<2)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Poruka je prekratka.'}});const property=await Nekretnina.findByPk(req.body.NekretninaId);if(!property||property.KorisnikId===req.korisnik.id)return res.status(400).json({error:{code:'INVALID_LISTING',message:'Razgovor nije moguće otvoriti za ovaj oglas.'}});let conversation;await sequelize.transaction(async transaction=>{[conversation]=await Razgovor.findOrCreate({where:{NekretninaId:property.id,PokretacId:req.korisnik.id},defaults:{VlasnikId:property.KorisnikId,OrganizacijaId:property.OrganizacijaId||null,status:'OPEN',zadnjaPorukaAt:new Date()},transaction});await Poruka.create({RazgovorId:conversation.id,PosiljalacId:req.korisnik.id,tekst},{transaction});await conversation.update({zadnjaPorukaAt:new Date(),status:'OPEN'},{transaction})});await notify(property.KorisnikId,'NEW_MESSAGE','Nova poruka',`Novi razgovor za oglas „${property.naziv}”.`,`/inbox/${conversation.id}`);await event('CONVERSATION_OPENED',req.korisnik.id,'RAZGOVOR',conversation.id,{NekretninaId:property.id});res.status(201);ok(res,{id:conversation.id})}catch(e){next(e)}};
async function participantConversation(id,userId){return Razgovor.findOne({where:{id,[Op.or]:[{PokretacId:userId},{VlasnikId:userId}]}})}
exports.conversation=async(req,res,next)=>{try{const r=await participantConversation(req.params.id,req.korisnik.id);if(!r)return res.status(404).json({error:{code:'NOT_FOUND',message:'Razgovor nije pronađen.'}});const full=await Razgovor.findByPk(r.id,{include:[{model:Nekretnina,attributes:['id','naziv','lokacija','slug']},{model:Poruka,as:'Poruke',include:[{model:Korisnik,as:'Posiljalac',attributes:['id','ime','prezime']}],order:[['id','ASC']]}]});const j=full.toJSON();j.jeVlasnik=full.VlasnikId===req.korisnik.id;j.Poruke=j.Poruke.map(p=>({...p,jeMoja:p.PosiljalacId===req.korisnik.id}));await Poruka.update({procitanoAt:new Date()},{where:{RazgovorId:r.id,PosiljalacId:{[Op.ne]:req.korisnik.id},procitanoAt:null}});ok(res,j)}catch(e){next(e)}};
exports.sendMessage=async(req,res,next)=>{try{if(!requireVerified(req,res))return;const r=await participantConversation(req.params.id,req.korisnik.id);const tekst=clean(req.body.tekst);if(!r||r.status==='BLOCKED')return res.status(403).json({error:{code:'FORBIDDEN',message:'Poruka nije dozvoljena.'}});if(tekst.length<1)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Poruka je prazna.'}});const p=await Poruka.create({RazgovorId:r.id,PosiljalacId:req.korisnik.id,tekst});await r.update({zadnjaPorukaAt:new Date(),status:'OPEN'});const recipient=r.PokretacId===req.korisnik.id?r.VlasnikId:r.PokretacId;await notify(recipient,'NEW_MESSAGE','Nova poruka','Imate novu privatnu poruku.',`/inbox/${r.id}`);await event('MESSAGE_SENT',req.korisnik.id,'RAZGOVOR',r.id);res.status(201);ok(res,{id:p.id})}catch(e){next(e)}};
exports.publishFaq=async(req,res,next)=>{try{const r=await Razgovor.findByPk(req.params.id);if(!r||r.VlasnikId!==req.korisnik.id)return res.status(403).json({error:{code:'FORBIDDEN',message:'Samo vlasnik oglasa može objaviti FAQ.'}});const pitanje=clean(req.body.pitanje,500),odgovor=clean(req.body.odgovor,1500);if(pitanje.length<5||odgovor.length<5)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Pitanje i odgovor moraju biti jasni i potpuni.'}});const faq=await JavniFaq.create({NekretninaId:r.NekretninaId,ObjavioId:req.korisnik.id,pitanje,odgovor,status:'PUBLISHED'});await event('FAQ_PUBLISHED',req.korisnik.id,'FAQ',faq.id,{NekretninaId:r.NekretninaId});res.status(201);ok(res,faq)}catch(e){next(e)}};

exports.appointments=async(req,res,next)=>{try{ok(res,await TerminPregleda.findAll({where:{[Op.or]:[{PodnosilacId:req.korisnik.id},{VlasnikId:req.korisnik.id}]},include:[{model:Nekretnina,attributes:['id','naziv','lokacija','slug']}],order:[['createdAt','DESC']]}))}catch(e){next(e)}};
exports.createAppointment=async(req,res,next)=>{try{if(!requireVerified(req,res))return;const times=(Array.isArray(req.body.termini)?req.body.termini:[]).filter(Boolean).slice(0,3).map(x=>new Date(x)).filter(x=>!Number.isNaN(x.getTime())&&x>new Date());if(!times.length)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Predložite najmanje jedan budući termin.'}});const property=await Nekretnina.findByPk(req.body.NekretninaId);if(!property||property.KorisnikId===req.korisnik.id)return res.status(400).json({error:{code:'INVALID_LISTING',message:'Termin nije moguće kreirati.'}});const t=await TerminPregleda.create({NekretninaId:property.id,PodnosilacId:req.korisnik.id,VlasnikId:property.KorisnikId,predlozeniTermin:times[0],alternativniTermini:times.slice(1),status:'PENDING'});await notify(property.KorisnikId,'APPOINTMENT_REQUEST','Novi prijedlog termina',`Korisnik želi pogledati „${property.naziv}”.`,'/termini');await event('APPOINTMENT_REQUESTED',req.korisnik.id,'TERMIN',t.id,{NekretninaId:property.id});res.status(201);ok(res,t)}catch(e){next(e)}};
exports.updateAppointment=async(req,res,next)=>{try{const t=await TerminPregleda.findByPk(req.params.id);if(!t||![t.PodnosilacId,t.VlasnikId].includes(req.korisnik.id))return res.status(404).json({error:{code:'NOT_FOUND',message:'Termin nije pronađen.'}});const allowed=t.VlasnikId===req.korisnik.id?['CONFIRMED','RESCHEDULED','DECLINED','COMPLETED']:['CANCELLED'];if(!allowed.includes(req.body.status))return res.status(400).json({error:{code:'INVALID_TRANSITION',message:'Promjena statusa nije dozvoljena.'}});await t.update({status:req.body.status,odgovor:clean(req.body.odgovor,500)||null,...(req.body.predlozeniTermin?{predlozeniTermin:new Date(req.body.predlozeniTermin)}:{})});await notify(t.PodnosilacId===req.korisnik.id?t.VlasnikId:t.PodnosilacId,'APPOINTMENT_UPDATED','Termin je ažuriran',`Novi status: ${t.status}`,'/termini');await event('APPOINTMENT_STATUS_CHANGED',req.korisnik.id,'TERMIN',t.id,{status:t.status});ok(res,t)}catch(e){next(e)}};

exports.offers=async(req,res,next)=>{try{ok(res,await PregovarackaPonuda.findAll({where:{[Op.or]:[{PonudjacId:req.korisnik.id},{PrimaocId:req.korisnik.id}]},include:[{model:Nekretnina,attributes:['id','naziv','slug']}],order:[['createdAt','DESC']]}))}catch(e){next(e)}};
exports.createOffer=async(req,res,next)=>{try{if(!requireVerified(req,res))return;const iznos=Number(req.body.iznos);const property=await Nekretnina.findByPk(req.body.NekretninaId);if(!property||property.KorisnikId===req.korisnik.id||!Number.isFinite(iznos)||iznos<=0)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Ponuda nije važeća.'}});const p=await PregovarackaPonuda.create({NekretninaId:property.id,PonudjacId:req.korisnik.id,PrimaocId:property.KorisnikId,iznos,poruka:clean(req.body.poruka),status:'SUBMITTED'});await notify(property.KorisnikId,'NEW_OFFER','Nova neobavezujuća ponuda',`Primili ste ponudu za „${property.naziv}”.`,'/ponude');await event('OFFER_SUBMITTED',req.korisnik.id,'PONUDA',p.id,{NekretninaId:property.id});res.status(201);ok(res,p)}catch(e){next(e)}};
exports.updateOffer=async(req,res,next)=>{try{const p=await PregovarackaPonuda.findByPk(req.params.id);if(!p||![p.PonudjacId,p.PrimaocId].includes(req.korisnik.id))return res.status(404).json({error:{code:'NOT_FOUND',message:'Ponuda nije pronađena.'}});const allowed=p.PrimaocId===req.korisnik.id?['ACCEPTED','REJECTED','COUNTERED']:['WITHDRAWN','COUNTERED'];if(!allowed.includes(req.body.status))return res.status(400).json({error:{code:'INVALID_TRANSITION',message:'Promjena statusa nije dozvoljena.'}});await p.update({status:req.body.status});await notify(p.PonudjacId===req.korisnik.id?p.PrimaocId:p.PonudjacId,'OFFER_UPDATED','Ponuda je ažurirana',`Novi status: ${p.status}`,'/ponude');await event('OFFER_STATUS_CHANGED',req.korisnik.id,'PONUDA',p.id,{status:p.status});ok(res,p)}catch(e){next(e)}};

exports.organizations=async(req,res,next)=>{try{const rows=await Organizacija.findAll({where:{status:'VERIFIED'},attributes:['id','naziv','slug','opis','grad','status',[literal('(SELECT COUNT(*) FROM nekretnina n WHERE n.OrganizacijaId = Organizacija.id AND n.status = \'PUBLISHED\')'),'brojOglasa']],order:[['naziv','ASC']]});ok(res,rows)}catch(e){next(e)}};
exports.organization=async(req,res,next)=>{try{const o=await Organizacija.findOne({where:{slug:req.params.slug,status:'VERIFIED'},attributes:['id','naziv','slug','opis','grad','telefon','web','status']});if(!o)return res.status(404).json({error:{code:'NOT_FOUND',message:'Agencija nije pronađena.'}});ok(res,o)}catch(e){next(e)}};
exports.createOrganization=async(req,res,next)=>{try{if(!requireVerified(req,res))return;const naziv=clean(req.body.naziv,160);if(naziv.length<2)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Naziv je obavezan.'}});const base=clean(req.body.slug||naziv,180).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let o;await sequelize.transaction(async transaction=>{o=await Organizacija.create({naziv,slug:`${base}-${Date.now().toString(36)}`,opis:clean(req.body.opis),grad:clean(req.body.grad,100),registracijskiBroj:clean(req.body.registracijskiBroj,100),KreatorId:req.korisnik.id,status:'PENDING'},{transaction});await ClanstvoOrganizacije.create({OrganizacijaId:o.id,KorisnikId:req.korisnik.id,uloga:'OWNER',status:'ACTIVE'},{transaction})});await event('ORGANIZATION_CREATED',req.korisnik.id,'ORGANIZACIJA',o.id);res.status(201);ok(res,o)}catch(e){next(e)}};

exports.notifications=async(req,res,next)=>{try{ok(res,await Obavijest.findAll({where:{KorisnikId:req.korisnik.id},order:[['createdAt','DESC']],limit:100}))}catch(e){next(e)}};
exports.readNotification=async(req,res,next)=>{try{const [count]=await Obavijest.update({procitanoAt:new Date()},{where:{id:req.params.id,KorisnikId:req.korisnik.id}});if(!count)return res.status(404).json({error:{code:'NOT_FOUND',message:'Obavijest nije pronađena.'}});res.status(204).end()}catch(e){next(e)}};
exports.notificationStream=(req,res)=>{res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});res.flushHeaders();const channel=`user:${req.korisnik.id}`;const listener=data=>res.write(`event: notification\ndata: ${JSON.stringify(data)}\n\n`);hub.on(channel,listener);const heartbeat=setInterval(()=>res.write(': heartbeat\n\n'),25000);req.on('close',()=>{clearInterval(heartbeat);hub.off(channel,listener)})};

exports.report=async(req,res,next)=>{try{const tip=String(req.body.tip||'').toUpperCase(),entitetId=Number(req.body.entitetId),razlog=clean(req.body.razlog,500);if(!['PORUKA','OGLAS','FAQ'].includes(tip)||!entitetId||razlog.length<5)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Prijava nije potpuna.'}});let snapshot=null;if(tip==='PORUKA'){const message=await Poruka.findByPk(entitetId,{include:[Razgovor]});if(!message||![message.Razgovor.PokretacId,message.Razgovor.VlasnikId].includes(req.korisnik.id))return res.status(403).json({error:{code:'FORBIDDEN',message:'Poruku ne možete prijaviti.'}});const around=await Poruka.findAll({where:{RazgovorId:message.RazgovorId,id:{[Op.between]:[Math.max(1,message.id-2),message.id+2]}},attributes:['id','tekst','PosiljalacId','createdAt']});snapshot={poruke:around.map(x=>x.toJSON())}}const report=await PrijavaSadrzaja.create({tip,entitetId,razlog,snapshot,PrijavioId:req.korisnik.id,status:'OPEN'});await event('CONTENT_REPORTED',req.korisnik.id,'PRIJAVA',report.id,{tip});res.status(201);ok(res,{id:report.id})}catch(e){next(e)}};

exports.adminDashboard=async(req,res,next)=>{try{const since=new Date(Date.now()-30*86400000);const [aktivniKorisnici,objavljeniOglasi,razgovori,cekaModeraciju,agencijeNaCekanju,otvorenePrijave,pregledi,favoriti,termini,ponude,zakljuceno]=await Promise.all([ActivityEvent.count({distinct:true,col:'ActorId',where:{createdAt:{[Op.gte]:since},ActorId:{[Op.ne]:null}}}),Nekretnina.count({where:{status:'PUBLISHED'}}),Razgovor.count({where:{createdAt:{[Op.gte]:since}}}),OglasRevizija.count({where:{status:'PENDING_REVIEW'}}),Organizacija.count({where:{status:'PENDING'}}),PrijavaSadrzaja.count({where:{status:'OPEN'}}),ActivityEvent.count({where:{tip:'LISTING_VIEWED',createdAt:{[Op.gte]:since}}}),OmiljenaNekretnina.count({where:{createdAt:{[Op.gte]:since}}}),TerminPregleda.count({where:{createdAt:{[Op.gte]:since}}}),PregovarackaPonuda.count({where:{createdAt:{[Op.gte]:since}}}),Nekretnina.count({where:{status:{[Op.in]:['SOLD','RENTED']},updatedAt:{[Op.gte]:since}}})]);ok(res,{aktivniKorisnici,objavljeniOglasi,razgovori,cekaModeraciju,agencijeNaCekanju,otvorenePrijave,funnel:{pregledi,favoriti,razgovori,termini,ponude,zakljuceno}})}catch(e){next(e)}};
exports.adminAnalytics=async(req,res,next)=>{try{const days=Math.min(365,Math.max(1,Number(req.query.period)||30)),since=new Date(Date.now()-days*86400000);const [pregledi,favoriti,razgovori,termini,ponude,zakljuceno]=await Promise.all([ActivityEvent.count({where:{tip:'LISTING_VIEWED',createdAt:{[Op.gte]:since}}}),OmiljenaNekretnina.count({where:{createdAt:{[Op.gte]:since}}}),Razgovor.count({where:{createdAt:{[Op.gte]:since}}}),TerminPregleda.count({where:{createdAt:{[Op.gte]:since}}}),PregovarackaPonuda.count({where:{createdAt:{[Op.gte]:since}}}),Nekretnina.count({where:{status:{[Op.in]:['SOLD','RENTED']},updatedAt:{[Op.gte]:since}}})]);ok(res,{pregledi,favoriti,razgovori,termini,ponude,zakljuceno,funnel:{pregledi,favoriti,razgovori,termini,ponude,zakljuceno}})}catch(e){next(e)}};
exports.adminUsers=async(req,res,next)=>{try{ok(res,await Korisnik.findAll({attributes:['id','ime','prezime','username','email','emailVerifiedAt','systemRole','suspendedAt','suspendedUntil','deletedAt','updatedAt'],order:[['id','DESC']],limit:200}))}catch(e){next(e)}};
exports.adminUser=async(req,res,next)=>{try{const u=await Korisnik.findByPk(req.params.id,{attributes:['id','ime','prezime','username','email','emailVerifiedAt','systemRole','suspendedAt','suspendedUntil','deletedAt']});if(!u)return res.status(404).json({error:{code:'NOT_FOUND',message:'Korisnik nije pronađen.'}});const j=u.toJSON();j.aktivnosti=await ActivityEvent.findAll({where:{ActorId:u.id,createdAt:{[Op.gte]:new Date(Date.now()-365*86400000)}},attributes:['id','tip','entitetTip','entitetId','metadata','createdAt'],order:[['createdAt','DESC']],limit:200});ok(res,j)}catch(e){next(e)}};
exports.adminUpdateUser=async(req,res,next)=>{try{const u=await Korisnik.findByPk(req.params.id);if(!u)return res.status(404).json({error:{code:'NOT_FOUND',message:'Korisnik nije pronađen.'}});if(u.id===req.korisnik.id&&['SUSPEND','DELETE'].includes(req.body.akcija))return res.status(400).json({error:{code:'SELF_ACTION',message:'Ne možete deaktivirati vlastiti nalog.'}});const akcija=req.body.akcija,razlog=clean(req.body.razlog,500)||'Administratorska odluka';if(akcija==='SUSPEND')await u.update({suspendedAt:new Date(),suspendedUntil:req.body.do?new Date(req.body.do):null,suspensionReason:razlog});else if(akcija==='REACTIVATE')await u.update({suspendedAt:null,suspendedUntil:null,suspensionReason:null,deletedAt:null});else if(akcija==='DELETE')await u.update({deletedAt:new Date()});else if(akcija==='SET_ROLE'){if(req.korisnik.systemRole!=='SUPER_ADMIN'||!['USER','ANALYST','MODERATOR','SUPER_ADMIN'].includes(req.body.uloga))return res.status(403).json({error:{code:'FORBIDDEN',message:'Samo super admin upravlja ulogama.'}});if(u.systemRole==='SUPER_ADMIN'&&req.body.uloga!=='SUPER_ADMIN'&&await Korisnik.count({where:{systemRole:'SUPER_ADMIN',deletedAt:null}})<=1)return res.status(400).json({error:{code:'LAST_ADMIN',message:'Posljednji super admin ne može biti degradiran.'}});await u.update({systemRole:req.body.uloga,admin:req.body.uloga==='SUPER_ADMIN'})}else return res.status(400).json({error:{code:'INVALID_ACTION',message:'Akcija nije dozvoljena.'}});await AdminAuditLog.create({AdminId:req.korisnik.id,akcija,entitetTip:'KORISNIK',entitetId:u.id,razlog,metadata:{uloga:req.body.uloga||null}});ok(res,{id:u.id,systemRole:u.systemRole,suspendedAt:u.suspendedAt,deletedAt:u.deletedAt})}catch(e){next(e)}};
exports.adminActivity=async(req,res,next)=>{try{ok(res,await ActivityEvent.findAll({include:[{model:Korisnik,as:'Actor',attributes:['id','username']}],attributes:['id','tip','entitetTip','entitetId','metadata','createdAt'],order:[['createdAt','DESC']],limit:300}))}catch(e){next(e)}};
exports.adminQueue=async(req,res,next)=>{try{if(req.params.kind==='nekretnine')return ok(res,await OglasRevizija.findAll({where:{status:'PENDING_REVIEW'},include:[{model:Nekretnina,attributes:['id','naziv']}],order:[['createdAt','ASC']]}));if(req.params.kind==='organizacije')return ok(res,await Organizacija.findAll({where:{status:'PENDING'},order:[['createdAt','ASC']]}));ok(res,await PrijavaSadrzaja.findAll({where:{status:'OPEN'},attributes:['id','tip','entitetId','razlog','status','createdAt'],order:[['createdAt','ASC']]}))}catch(e){next(e)}};
exports.adminDecision=async(req,res,next)=>{try{const kind=req.params.kind,id=req.params.id,approve=req.body.akcija==='APPROVE',razlog=clean(req.body.razlog,500)||'Administratorska odluka';let entity;if(kind==='organizacije'){entity=await Organizacija.findByPk(id);if(entity)await entity.update({status:approve?'VERIFIED':'REJECTED',razlogOdluke:razlog,verificiranaAt:approve?new Date():null})}else if(kind==='nekretnine'){entity=await OglasRevizija.findByPk(id);if(entity){await sequelize.transaction(async transaction=>{await entity.update({status:approve?'APPROVED':'REJECTED',razlogOdluke:razlog,PregledaoId:req.korisnik.id},{transaction});const listing=await Nekretnina.findByPk(entity.NekretninaId,{transaction,lock:transaction.LOCK.UPDATE});if(approve&&listing){const allowed=['tip_nekretnine','naziv','kvadratura','cijena','tip_grijanja','lokacija','godina_izgradnje','opis','namjena','grad','naselje','punaAdresa','latPriblizno','lngPriblizno','latTacno','lngTacno','brojSoba','brojKupatila','sprat','brojSpratova','parking','balkon','lift','namjestenost','stanje','energetskaKlasa','dostupnoOd','pogodnosti','OrganizacijaId','DodijeljeniAgentId'];const values={status:'PUBLISHED'};for(const key of allowed)if(entity.podaci?.[key]!==undefined)values[key]=entity.podaci[key];await listing.update(values,{transaction})}else if(listing&&listing.status==='PENDING_REVIEW')await listing.update({status:'REJECTED'},{transaction})})}}else{entity=await PrijavaSadrzaja.findByPk(id);if(entity)await entity.update({status:approve?'RESOLVED':'DISMISSED'})}if(!entity)return res.status(404).json({error:{code:'NOT_FOUND',message:'Predmet nije pronađen.'}});await AdminAuditLog.create({AdminId:req.korisnik.id,akcija:approve?'APPROVE':'REJECT',entitetTip:kind.toUpperCase(),entitetId:Number(id),razlog});ok(res,entity)}catch(e){next(e)}};
